import { describe, expect, test } from "bun:test";
import { themeBundle } from "../packages/tokens/generated/themes";
import {
  type InkdropThemeType,
  renderInkdropPackages,
} from "../packages/tokens/src/adapters/inkdrop";

const HEX = /^#[0-9a-f]{6}$/;
const THEME_TYPES: readonly InkdropThemeType[] = ["ui", "syntax", "preview"];

function fileContent(pack: ReturnType<typeof renderInkdropPackages>[number], path: string): string {
  const file = pack.files.find((candidate) => candidate.path === path);
  if (!file) throw new Error(`${pack.packageName} is missing ${path}`);
  return file.content;
}

function packageJson(pack: ReturnType<typeof renderInkdropPackages>[number]) {
  return JSON.parse(fileContent(pack, "package.json")) as {
    name: string;
    theme: InkdropThemeType;
    themeAppearance?: string;
    type?: string;
    styleSheets: string[];
    engines: { inkdrop: string };
  };
}

describe("Hue -> Inkdrop adapter", () => {
  const packages = renderInkdropPackages(themeBundle.themes);

  test("renders one UI, syntax, and preview package for every mood", () => {
    expect(packages).toHaveLength(9);
    expect(packages.map((pack) => pack.packageName)).toEqual([
      "hue-cung-theme",
      "hue-cung-syntax-theme",
      "hue-cung-preview-theme",
      "hue-huong-theme",
      "hue-huong-syntax-theme",
      "hue-huong-preview-theme",
      "hue-mua-theme",
      "hue-mua-syntax-theme",
      "hue-mua-preview-theme",
    ]);
  });

  test("writes Inkdrop package metadata for every generated package", () => {
    for (const pack of packages) {
      const metadata = packageJson(pack);
      expect(metadata.name).toBe(pack.packageName);
      expect(THEME_TYPES).toContain(metadata.theme);
      expect(metadata.theme).toBe(pack.themeType);
      expect(metadata.styleSheets).toEqual(["theme.css"]);
      expect(metadata.engines.inkdrop).toBe("^6.x");
    }
  });

  test("emits generated CSS with required slots per theme type", () => {
    for (const pack of packages) {
      const css = fileContent(pack, "styles/theme.css");
      expect(css).toContain("Generated by scripts/build.ts. Do not edit.");
      expect(css).toContain(`color-scheme: ${pack.moodId === "cung" ? "light" : "dark"};`);

      if (pack.themeType === "ui") {
        expect(css).toContain("--page-background:");
        expect(css).toContain("--sidebar-background:");
        expect(css).toContain("--note-list-bar-background:");
        expect(css).toContain("--editor-background:");
      }
      if (pack.themeType === "syntax") {
        expect(css).toContain("--editor-foreground-color:");
        expect(css).toContain("--syntax-keyword-color:");
        expect(css).toContain("--md-codeblock-background-color:");
      }
      if (pack.themeType === "preview") {
        expect(css).toContain(".mde-preview");
        expect(css).toContain("--md-blockquote-border-color:");
        expect(css).toContain("--syntax-string-color:");
      }
    }
  });

  test("uses resolved hex values in CSS", () => {
    for (const pack of packages) {
      const css = fileContent(pack, "styles/theme.css");
      const matches = css.match(/#[0-9a-f]{6}/g) ?? [];
      expect(matches.length).toBeGreaterThan(20);
      for (const value of matches) expect(value).toMatch(HEX);
    }
  });

  // Regression: Inkdrop only registers a theme that declares themeAppearance and
  // resolves its stylesheet relative to styles/ (bare filename). Missing either
  // makes the app silently fall back to its default theme.
  test("declares the metadata Inkdrop needs to load the theme", () => {
    for (const pack of packages) {
      const metadata = packageJson(pack);
      expect(metadata.styleSheets).toEqual(["theme.css"]);
      expect(metadata.themeAppearance).toBe(pack.moodId === "cung" ? "light" : "dark");
      // Only UI themes carry type: "module", matching the built-in themes.
      expect(metadata.type).toBe(pack.themeType === "ui" ? "module" : undefined);
    }
  });

  // Regression: Inkdrop colors editor headings from the per-level slots and the
  // rendered preview from the --mde-preview-* namespace. Emitting only the base
  // --syntax-heading-color / --md-* left headings and preview on Inkdrop defaults.
  test("emits the full variable contract Inkdrop actually consumes", () => {
    const syntax = packages.filter((pack) => pack.themeType === "syntax");
    for (const pack of syntax) {
      const css = fileContent(pack, "styles/theme.css");
      for (let level = 1; level <= 6; level += 1) {
        expect(css).toContain(`--syntax-heading-${level}-color:`);
      }
      // Correct gutter-border property name (not the *-color variant we shipped before).
      expect(css).toContain("--editor-gutter-border-right:");
      expect(css).not.toContain("--editor-gutter-border-right-color:");
    }
    for (const pack of packages.filter((p) => p.themeType === "preview")) {
      const css = fileContent(pack, "styles/theme.css");
      expect(css).toContain("--mde-preview-heading-color:");
      expect(css).toContain("--mde-preview-link-color:");
    }
  });

  // Regression: tag/label chips are Hue-tinted via the chromatic families, each
  // with a color-mix background derived from the canvas.
  test("emits Hue-tinted tag chip colors in UI packages", () => {
    for (const pack of packages.filter((p) => p.themeType === "ui")) {
      const css = fileContent(pack, "styles/theme.css");
      for (const family of ["red", "yellow", "green", "blue", "violet"]) {
        expect(css).toContain(`--${family}-background:`);
      }
      expect(css).toContain("color-mix(in srgb,");
    }
  });
});
