import { describe, expect, test } from "bun:test";
import { themeBundle } from "../packages/tokens/generated/themes";
import { neovimManifest, renderNeovimFiles } from "../packages/tokens/src/adapters/neovim";
import { validateManifest } from "../packages/tokens/src/contract";

const HEX = /#[0-9A-F]{6}/;
const moods = [...themeBundle.themes];
const files = renderNeovimFiles(moods);
const file = (path: string): string => {
  const found = files.find((candidate) => candidate.path === path);
  if (!found) throw new Error(`missing generated file ${path}`);
  return found.content;
};

describe("Hue → Neovim adapter", () => {
  test("supports every contract family, omits none", () => {
    expect(() => validateManifest("neovim", neovimManifest)).not.toThrow();
    expect(neovimManifest.omits).toEqual({});
  });

  test("emits the shared lua tree plus per-mood entrypoints", () => {
    const paths = files.map((f) => f.path).sort();
    expect(paths).toEqual(
      [
        "lua/hue/palette.lua",
        "lua/hue/groups.lua",
        "lua/hue/colors.lua",
        "lua/hue/util.lua",
        "lua/hue/init.lua",
        ...moods.flatMap((m) => [`colors/hue-${m.id}.lua`, `lua/lualine/themes/hue-${m.id}.lua`]),
      ].sort(),
    );
  });

  test("every generated file carries the do-not-edit header and is non-empty", () => {
    for (const { content } of files) {
      expect(content.startsWith("-- Generated by scripts/build.ts. Do not edit.")).toBe(true);
      expect(content.trim().length).toBeGreaterThan(0);
    }
  });

  test("groups.lua only references roles that exist on every mood", () => {
    const groups = file("lua/hue/groups.lua");
    const referenced = [...groups.matchAll(/c\["([^"]+)"\]/g)].map((m) => m[1]);
    expect(referenced.length).toBeGreaterThan(0);
    for (const mood of moods) {
      const roles = Object.keys(mood.semantic);
      for (const role of referenced) {
        expect(roles).toContain(role);
      }
    }
  });

  test("palette.lua resolves 16 valid-hex terminal colors per mood", () => {
    const palette = file("lua/hue/palette.lua");
    for (const mood of moods) {
      // The terminal block for each mood: from its `terminal = {` to the next `}`.
      const block = palette.match(
        new RegExp(`${mood.id} = \\{[\\s\\S]*?terminal = \\{([\\s\\S]*?)\\n {4}\\}`),
      );
      expect(block, `terminal block for ${mood.id}`).not.toBeNull();
      const colors = [...(block?.[1] ?? "").matchAll(/"(#[0-9A-F]{6})"/g)];
      expect(colors).toHaveLength(16);
    }
  });

  test("exposes a public color API (colors/raw/util) from init.lua", () => {
    const init = file("lua/hue/init.lua");
    expect(init).toContain("M.colors = colors.get");
    expect(init).toContain("M.raw = colors.raw");
    expect(init).toContain('M.util = require("hue.util")');

    const colors = file("lua/hue/colors.lua");
    expect(colors).toContain("function M.get(mood)");
    expect(colors).toContain("function M.raw(mood)");

    const util = file("lua/hue/util.lua");
    for (const fn of ["M.blend", "M.darken", "M.lighten"]) {
      expect(util).toContain(`function ${fn}`);
    }
  });

  test("supports a transparent option that clears backgrounds", () => {
    const init = file("lua/hue/init.lua");
    expect(init).toContain("transparent = false");
    expect(init).toContain("if M.options.transparent then");
    expect(init).toContain("hl.bg = nil");
    expect(init).toContain("TRANSPARENT_GROUPS");
    // Core editor + popular plugin containers must be among the cleared groups.
    for (const group of ["Normal", "NormalFloat", "SnacksPickerNormal", "NoicePopup"]) {
      expect(init).toMatch(new RegExp(`TRANSPARENT_GROUPS = \\{[\\s\\S]*"${group}"[\\s\\S]*\\}`));
    }
  });

  test("colors entrypoints load their mood", () => {
    for (const mood of moods) {
      expect(file(`colors/hue-${mood.id}.lua`)).toContain(`require("hue").load("${mood.id}")`);
    }
  });

  test("lualine themes expose the five mode sections in valid hex", () => {
    for (const mood of moods) {
      const theme = file(`lua/lualine/themes/hue-${mood.id}.lua`);
      for (const mode of ["normal", "insert", "visual", "replace", "command", "inactive"]) {
        expect(theme).toContain(`${mode} =`);
      }
      for (const value of theme.matchAll(/(fg|bg) = "([^"]+)"/g)) {
        expect(value[2]).toMatch(HEX);
      }
    }
  });
});
