// Hue → Ghostty adapter. Emits a Ghostty theme file per mood: the 16-color ANSI
// palette (derived from primitives) plus background/foreground/cursor/selection
// mapped from semantic roles. Ghostty theme files only expose these slots, so
// border/status/syntax are omitted explicitly.
//
// Typography policy: a Ghostty *theme* file carries colors only; the user's
// font stays in their own config.

import type { AdapterManifest } from "../contract";
import { type ResolvedMood, terminalColors } from "./terminal";

// Ghostty theme files map color/cursor/selection but have no slots for borders,
// status roles, or syntax highlighting.
export const ghosttyManifest = {
  supports: ["surface", "text", "accent"],
  omits: {
    border: "Ghostty theme files have no border color slot",
    status: "Ghostty theme files have no status/diagnostic slots",
    syntax: "Ghostty theme files have no syntax-highlighting slots",
  },
} satisfies AdapterManifest;

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

/** Render one Ghostty theme file. */
function renderGhosttyTheme(mood: ResolvedMood): string {
  const palette = terminalColors(mood)
    .map((color, index) => `palette = ${index}=${color}`)
    .join("\n");
  return `# Generated by scripts/build.ts. Do not edit.
# ${mood.label} — Hue theme for Ghostty.

${palette}

background = ${role(mood, "surface.canvas")}
foreground = ${role(mood, "text.primary")}
cursor-color = ${role(mood, "accent.primary")}
cursor-text = ${role(mood, "surface.canvas")}
selection-background = ${role(mood, "surface.selected")}
selection-foreground = ${role(mood, "text.primary")}
`;
}

/**
 * Render every mood's Ghostty theme file. Paths are relative to the
 * `packages/terminal-themes/` package root. Ghostty loads a file named
 * `hue-<mood>` placed in its `themes/` directory via `theme = hue-<mood>`.
 */
export function renderGhosttyFiles(
  moods: ResolvedMood[],
): Array<{ path: string; content: string }> {
  return moods.map((mood) => ({
    path: `ghostty/hue-${mood.id}`,
    content: renderGhosttyTheme(mood),
  }));
}
