// Hue → herdr adapter. Emits a [theme.custom] TOML fragment per mood targeting
// herdr's real theme slots. herdr (0.7.3) deserializes [theme.custom] into a
// catppuccin-shaped `CustomThemeColors` struct and silently ignores unknown
// keys — the tokens documented by `herdr --default-config` are only a subset,
// and terminal-style keys (background, foreground, cursor, selection_*, the
// ANSI names) are no-ops. The accepted slots, with the UI regions each one
// paints (verified empirically by probing a live server with unique colors
// per slot and parsing a captured client frame):
//
//   accent       active tab bg, menu indicator (overrides [ui].accent)
//   panel_bg     tab-strip bg; also the active tab's label fg
//   surface0     inactive tab bg
//   surface1     (not observed; next neutral step)
//   surface_dim  selected sidebar row bg + divider lines
//   overlay0     section headers, branch names, menu chrome text
//   overlay1     inactive tab label fg
//   text         focused workspace / agent row titles
//   subtext0     unfocused workspace names
//   mauve        focused workspace's branch name
//   green/yellow/red/blue/teal/peach  agent-state + status colors
//                (yellow = working; green/red presumed idle/blocked)
//
// herdr paints no app background — the terminal theme shows through — and has
// no syntax slots; pane content is colored by the terminal (Ghostty) theme.
//
// herdr has no scriptable theme API (no `herdr theme` subcommand, no socket
// method, no plugin hook) — the only way to change its colors is editing
// config.toml's [theme.custom] and calling `herdr server reload-config`. So
// unlike Ghostty/tmux, these fragments aren't sourced directly: the
// herdr-plugin package's apply.sh splices the active mood's fragment into
// config.toml and reloads.

import type { AdapterManifest } from "../contract";
import type { ResolvedMood } from "./terminal";

export const herdrManifest = {
  supports: ["surface", "text", "border", "accent", "status"],
  omits: {
    syntax: "herdr has no syntax-highlighting slots; pane content is colored by the terminal theme",
  },
} satisfies AdapterManifest;

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

function primitive(mood: ResolvedMood, key: string): string {
  const value = mood.primitive[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing primitive ${key}`);
  return value;
}

/** Render one herdr [theme.custom] fragment, spliced in by the plugin's apply.sh. */
function renderHerdrTheme(mood: ResolvedMood): string {
  return `[theme.custom]
# Generated by scripts/build.ts. Do not edit.
# ${mood.label} — Hue theme for herdr.
# apply.sh also copies \`accent\` into [ui].accent; keep it first.
accent = "${role(mood, "accent.primary")}"
panel_bg = "${role(mood, "surface.raised")}"
surface0 = "${role(mood, "surface.selected")}"
surface1 = "${role(mood, "border.subtle")}"
surface_dim = "${role(mood, "surface.selected")}"
overlay0 = "${primitive(mood, "fog")}"
overlay1 = "${primitive(mood, "mist")}"
text = "${role(mood, "text.primary")}"
subtext0 = "${role(mood, "text.secondary")}"
mauve = "${role(mood, "accent.secondary")}"
green = "${role(mood, "status.success")}"
yellow = "${role(mood, "status.warning")}"
red = "${role(mood, "status.error")}"
blue = "${role(mood, "status.info")}"
teal = "${role(mood, "status.info")}"
peach = "${role(mood, "status.warning")}"
`;
}

/**
 * Render every mood's herdr fragment. Paths are relative to the
 * `packages/herdr-plugin/` package root.
 */
export function renderHerdrFiles(moods: ResolvedMood[]): Array<{ path: string; content: string }> {
  return moods.map((mood) => ({
    path: `themes/hue-${mood.id}.toml`,
    content: renderHerdrTheme(mood),
  }));
}
