// Hue → herdr adapter. Emits a [theme.custom] TOML fragment per mood: the base
// 8 ANSI colors plus panel/background/foreground/cursor/selection/accent
// mapped from semantic roles. herdr's [theme.custom] only exposes the color
// tokens documented by `herdr --default-config` (panel_bg, accent, background,
// foreground, cursor, selection_background, selection_foreground, and the 8
// base ANSI names) — it has no border/status/syntax slots to override.
//
// herdr has no scriptable theme API (no `herdr theme` subcommand, no socket
// method, no plugin hook) — the only way to change its colors is editing
// config.toml's [theme.custom] and calling `herdr server reload-config`. So
// unlike Ghostty/tmux, these fragments aren't sourced directly: the
// herdr-plugin package's apply.sh splices the active mood's fragment into
// config.toml and reloads.

import type { AdapterManifest } from "../contract";
import { type ResolvedMood, terminalColors } from "./terminal";

export const herdrManifest = {
  supports: ["surface", "text", "accent"],
  omits: {
    border: "herdr's [theme.custom] has no border color slot",
    status: "herdr's [theme.custom] has no status/diagnostic slots",
    syntax: "herdr's [theme.custom] has no syntax-highlighting slots",
  },
} satisfies AdapterManifest;

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

const ANSI_NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];

/** Render one herdr [theme.custom] fragment, spliced in by the plugin's apply.sh. */
function renderHerdrTheme(mood: ResolvedMood): string {
  const ansi = terminalColors(mood).slice(0, 8);
  const ansiLines = ANSI_NAMES.map((name, index) => `${name} = "${ansi[index]}"`).join("\n");

  return `[theme.custom]
# Generated by scripts/build.ts. Do not edit.
# ${mood.label} — Hue theme for herdr.
panel_bg = "${role(mood, "surface.raised")}"
background = "${role(mood, "surface.canvas")}"
foreground = "${role(mood, "text.primary")}"
accent = "${role(mood, "accent.primary")}"
cursor = "${role(mood, "accent.primary")}"
selection_background = "${role(mood, "surface.selected")}"
selection_foreground = "${role(mood, "text.primary")}"
${ansiLines}
`;
}

/**
 * Render every mood's herdr fragment. Paths are relative to the
 * `packages/herdr-plugin/` package root.
 */
export function renderHerdrFiles(moods: ResolvedMood[]): Array<{ path: string; content: string }> {
  return moods.map((mood) => ({
    path: `themes/hue-${mood.id}.toml`,
    content: renderHerdrTheme(mood),
  }));
}
