// Hue -> Inkdrop adapter. Emits one installable Inkdrop theme package for each
// mood/theme-type pair. Inkdrop v6 themes are CSS packages with a `theme`
// metadata field (`ui`, `syntax`, or `preview`) and one or more stylesheets.

import type { SemanticToken } from "../../generated/themes";
import type { AdapterManifest } from "../contract";
import type { ResolvedMood } from "./terminal";

export const inkdropManifest = {
  supports: ["surface", "text", "border", "accent", "status", "syntax"],
  omits: {},
} satisfies AdapterManifest;

export type InkdropThemeType = "ui" | "syntax" | "preview";

export type InkdropPackage = {
  packageName: string;
  packagePath: string;
  moodId: string;
  themeType: InkdropThemeType;
  files: Array<{ path: string; content: string }>;
};

const THEME_TYPES: readonly InkdropThemeType[] = ["ui", "syntax", "preview"];

function role(mood: ResolvedMood, key: SemanticToken): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

function cssVars(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([key, value]) => `  ${key}: ${cssValue(value)};`)
    .join("\n");
}

function cssValue(value: string): string {
  return value.replace(/#[0-9A-F]{6}/gi, (hex) => hex.toLowerCase());
}

function packageName(mood: ResolvedMood, type: InkdropThemeType): string {
  return `hue-${mood.id}-${type}-theme`;
}

function themeDescription(mood: ResolvedMood, type: InkdropThemeType): string {
  const label = type === "ui" ? "UI" : type.charAt(0).toUpperCase() + type.slice(1);
  return `${mood.label} ${label} Theme for Inkdrop`;
}

function renderPackageJson(mood: ResolvedMood, type: InkdropThemeType): string {
  return `${JSON.stringify(
    {
      name: packageName(mood, type),
      version: "0.1.0",
      theme: type,
      description: themeDescription(mood, type),
      styleSheets: ["styles/theme.css"],
      keywords: ["inkdrop", "markdown", "hue-theme"],
      repository: {
        type: "git",
        url: "https://github.com/crafts69guy/hue-theme",
        directory: `packages/${packageName(mood, type)}`,
      },
      bugs: {
        url: "https://github.com/crafts69guy/hue-theme/issues",
      },
      homepage: "https://github.com/crafts69guy/hue-theme#readme",
      author: "crafts69guy",
      license: "MIT",
      engines: { inkdrop: "^6.x" },
    },
    null,
    2,
  )}\n`;
}

function renderReadme(mood: ResolvedMood, type: InkdropThemeType): string {
  return `# ${packageName(mood, type)}

${themeDescription(mood, type)}.

This package is generated from the Hue Theme token contract. Do not edit the
CSS by hand; update the source tokens or Inkdrop adapter and run the token build.

## Install locally

\`\`\`fish
ipm install ./packages/${packageName(mood, type)}
\`\`\`
`;
}

function renderLicense(): string {
  return `MIT License

Generated package for Hue Theme. See the repository root LICENSE for the full
license text.
`;
}

function renderHeader(mood: ResolvedMood, type: InkdropThemeType): string {
  return `/* Generated by scripts/build.ts. Do not edit.
 * ${themeDescription(mood, type)}.
 */
`;
}

function renderUiCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--primary-color": role(mood, "accent.primary"),
    "--secondary-color": role(mood, "accent.secondary"),
    "--light-primary-color": role(mood, "accent.primary"),
    "--light-secondary-color": role(mood, "text.secondary"),
    "--page-background": role(mood, "surface.canvas"),
    "--text-color": role(mood, "text.primary"),
    "--link-color": role(mood, "text.accent"),
    "--link-hover-color": role(mood, "accent.primary"),
    "--highlight-background": role(mood, "surface.selected"),
    "--highlight-color": role(mood, "text.primary"),
    "--input-background": role(mood, "surface.raised"),
    "--input-color": role(mood, "text.primary"),
    "--input-placeholder-color": role(mood, "text.secondary"),
    "--focused-form-border-color": role(mood, "accent.primary"),
    "--focused-form-muted-border-color": role(mood, "accent.secondary"),
    "--focused-outline-color": role(mood, "surface.selected"),
    "--loader-line-color": role(mood, "accent.primary"),
    "--positive-color": role(mood, "status.success"),
    "--positive-background-color": role(mood, "surface.raised"),
    "--positive-border-color": role(mood, "status.success"),
    "--positive-header-color": role(mood, "status.success"),
    "--positive-text-color": role(mood, "status.success"),
    "--negative-color": role(mood, "status.error"),
    "--negative-background-color": role(mood, "surface.raised"),
    "--negative-border-color": role(mood, "status.error"),
    "--negative-header-color": role(mood, "status.error"),
    "--negative-text-color": role(mood, "status.error"),
    "--info-color": role(mood, "status.info"),
    "--info-background-color": role(mood, "surface.raised"),
    "--info-border-color": role(mood, "status.info"),
    "--info-header-color": role(mood, "status.info"),
    "--info-text-color": role(mood, "status.info"),
    "--warning-color": role(mood, "status.warning"),
    "--warning-background-color": role(mood, "surface.raised"),
    "--warning-border-color": role(mood, "status.warning"),
    "--warning-header-color": role(mood, "status.warning"),
    "--warning-text-color": role(mood, "status.warning"),
    "--success-color": role(mood, "status.success"),
    "--success-background-color": role(mood, "surface.raised"),
    "--success-border-color": role(mood, "status.success"),
    "--success-header-color": role(mood, "status.success"),
    "--success-text-color": role(mood, "status.success"),
    "--error-color": role(mood, "status.error"),
    "--error-background-color": role(mood, "surface.raised"),
    "--error-border-color": role(mood, "status.error"),
    "--error-header-color": role(mood, "status.error"),
    "--error-text-color": role(mood, "status.error"),
    "--dark-text-color": role(mood, "text.primary"),
    "--muted-text-color": role(mood, "text.secondary"),
    "--light-text-color": role(mood, "text.secondary"),
    "--unselected-text-color": role(mood, "text.secondary"),
    "--hovered-text-color": role(mood, "text.primary"),
    "--pressed-text-color": role(mood, "text.primary"),
    "--selected-text-color": role(mood, "text.primary"),
    "--border-color": role(mood, "border.subtle"),
    "--strong-border-color": role(mood, "accent.secondary"),
    "--internal-border-color": role(mood, "border.subtle"),
    "--selected-border-color": role(mood, "accent.primary"),
    "--solid-internal-border-color": role(mood, "border.subtle"),
    "--solid-border-color": role(mood, "border.subtle"),
    "--solid-selected-border-color": role(mood, "accent.primary"),
    "--primary-color-hover": role(mood, "accent.primary"),
    "--primary-color-focus": role(mood, "accent.primary"),
    "--secondary-color-hover": role(mood, "accent.secondary"),
    "--menu-background": role(mood, "surface.raised"),
    "--menu-item-text-color": role(mood, "text.primary"),
    "--menu-hover-item-background": role(mood, "surface.selected"),
    "--menu-hover-item-color": role(mood, "text.primary"),
    "--menu-active-item-background": role(mood, "surface.selected"),
    "--menu-active-item-color": role(mood, "text.primary"),
    "--popup-background": role(mood, "surface.raised"),
    "--popup-color": role(mood, "text.primary"),
    "--popup-border-color": role(mood, "border.subtle"),
    "--tooltip-background": role(mood, "surface.raised"),
    "--tooltip-color": role(mood, "text.secondary"),
    "--tooltip-border-color": role(mood, "border.subtle"),
    "--table-background": role(mood, "surface.canvas"),
    "--table-header-background": role(mood, "surface.raised"),
    "--table-header-color": role(mood, "text.primary"),
    "--checkbox-color": role(mood, "text.primary"),
    "--checkbox-background": role(mood, "surface.raised"),
    "--checkbox-border": `1px solid ${role(mood, "border.subtle")}`,
    "--checkbox-active-background": role(mood, "accent.primary"),
    "--checkbox-active-border-color": role(mood, "accent.primary"),
    "--dropdown-menu-background": role(mood, "surface.raised"),
    "--dropdown-menu-border-color": role(mood, "border.subtle"),
    "--dropdown-menu-item-color": role(mood, "text.primary"),
    "--dropdown-hovered-item-background": role(mood, "surface.selected"),
    "--dropdown-hovered-item-color": role(mood, "text.primary"),
    "--modal-box-header-background": role(mood, "surface.raised"),
    "--modal-box-content-background": role(mood, "surface.canvas"),
    "--modal-box-actions-background": role(mood, "surface.raised"),
    "--sidebar-background": role(mood, "surface.raised"),
    "--sidebar-border-right": `1px solid ${role(mood, "border.subtle")}`,
    "--sidebar-menu-item-inactive-background": role(mood, "surface.canvas"),
    "--sidebar-menu-item-active-background": role(mood, "surface.selected"),
    "--sidebar-menu-section-color": role(mood, "text.secondary"),
    "--sidebar-menu-section-separator-color": role(mood, "border.subtle"),
    "--sidebar-menu-item-color": role(mood, "text.secondary"),
    "--sidebar-menu-active-item-color": role(mood, "text.primary"),
    "--sidebar-sync-status-view-background": role(mood, "surface.canvas"),
    "--sidebar-sync-status-view-text-color": role(mood, "text.secondary"),
    "--scrollbar-track-background": role(mood, "surface.canvas"),
    "--scrollbar-thumb-background": role(mood, "border.subtle"),
    "--note-list-bar-background": role(mood, "surface.raised"),
    "--note-list-bar-border-right": `1px solid ${role(mood, "border.subtle")}`,
    "--note-list-view-item-header-color": role(mood, "text.primary"),
    "--note-list-view-item-color": role(mood, "text.secondary"),
    "--note-list-view-item-separator-border": `1px solid ${role(mood, "border.subtle")}`,
    "--note-list-view-item-date-color": role(mood, "accent.primary"),
    "--note-list-view-item-selected-background": role(mood, "surface.selected"),
    "--note-list-view-item-active-background": role(mood, "surface.selected"),
    "--note-search-bar-input-background": role(mood, "surface.canvas"),
    "--editor-background": role(mood, "surface.canvas"),
    "--editor-header-title-input-background": "transparent",
    "--editor-floating-actions-background": role(mood, "surface.raised"),
    "--editor-drawer-background": role(mood, "surface.raised"),
    "--editor-drawer-border-left": `1px solid ${role(mood, "border.subtle")}`,
    "--header-note-menu-color": role(mood, "text.secondary"),
    "--notification-item-background": role(mood, "surface.raised"),
    "--preferences-sidebar-background": role(mood, "surface.raised"),
    "--preferences-sidebar-item-active-background": role(mood, "surface.selected"),
    "--preferences-view-background": role(mood, "surface.canvas"),
  };

  return `${renderHeader(mood, "ui")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}
`;
}

function renderSyntaxCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--editor-foreground-color": role(mood, "text.primary"),
    "--editor-background-color": role(mood, "surface.canvas"),
    "--editor-caret-color": role(mood, "accent.primary"),
    "--editor-selection-background": role(mood, "surface.selected"),
    "--editor-focused-selection-background": role(mood, "surface.selected"),
    "--editor-active-line-background-color": role(mood, "surface.raised"),
    "--editor-special-char-color": role(mood, "border.subtle"),
    "--editor-spelling-error-color": role(mood, "status.error"),
    "--editor-gutter-border-right-color": role(mood, "border.subtle"),
    "--editor-gutter-color": role(mood, "text.secondary"),
    "--editor-gutter-background-color": "transparent",
    "--editor-gutter-background-solid-color": role(mood, "surface.canvas"),
    "--editor-active-line-gutter-background-color": role(mood, "surface.raised"),
    "--editor-panel-background-color": role(mood, "surface.raised"),
    "--editor-panel-color": role(mood, "text.secondary"),
    "--editor-panel-border-color": role(mood, "border.subtle"),
    "--editor-tooltip-border-color": role(mood, "border.subtle"),
    "--editor-tooltip-background-color": role(mood, "surface.raised"),
    "--editor-tooltip-autocomplete-item-selected-background-color": role(mood, "surface.selected"),
    "--editor-tooltip-autocomplete-item-selected-color": role(mood, "text.primary"),
    "--editor-inline-tooltip-color": role(mood, "text.secondary"),
    "--editor-inline-tooltip-background-color": role(mood, "surface.raised"),
    "--editor-completion-label": role(mood, "text.secondary"),
    "--editor-completion-matched-text-color": role(mood, "accent.primary"),
    "--editor-completion-detail-color": role(mood, "accent.secondary"),
    "--editor-matching-bracket-outline": `1px solid ${role(mood, "accent.secondary")}`,
    "--editor-nonmatching-bracket-outline": `1px solid ${role(mood, "status.error")}`,
    "--editor-selection-match-background-color": role(mood, "surface.raised"),
    "--editor-search-match-background-color": role(mood, "status.notice"),
    "--editor-search-match-selected-background-color": role(mood, "status.warning"),
    "--editor-search-match-selected-outline": `1px solid ${role(mood, "status.warning")}`,
    "--editor-placeholder-color": role(mood, "text.secondary"),
    "--editor-nes-ghost-color": role(mood, "text.secondary"),
    "--editor-highlight-space-color": role(mood, "surface.raised"),
    "--editor-trailing-space-background-color": role(mood, "status.error"),
    "--syntax-comment-color": role(mood, "syntax.comment"),
    "--syntax-name-color": role(mood, "text.primary"),
    "--syntax-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-name-standard-color": role(mood, "syntax.function"),
    "--syntax-name-definition-color": role(mood, "syntax.function"),
    "--syntax-name-function-color": role(mood, "syntax.function"),
    "--syntax-variable-name-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-variable-name-standard-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-definition-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-function-color": role(mood, "syntax.function"),
    "--syntax-property-name-color": role(mood, "syntax.property"),
    "--syntax-property-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-property-name-standard-color": role(mood, "syntax.property"),
    "--syntax-property-name-definition-color": role(mood, "syntax.property"),
    "--syntax-property-name-function-color": role(mood, "syntax.function"),
    "--syntax-tag-name-color": role(mood, "syntax.keyword"),
    "--syntax-attribute-name-color": role(mood, "syntax.property"),
    "--syntax-class-name-color": role(mood, "syntax.type"),
    "--syntax-label-name-color": role(mood, "syntax.keyword"),
    "--syntax-namespace-color": role(mood, "syntax.type"),
    "--syntax-macro-name-color": role(mood, "syntax.function"),
    "--syntax-string-color": role(mood, "syntax.string"),
    "--syntax-number-color": role(mood, "syntax.number"),
    "--syntax-literal-color": role(mood, "syntax.constant"),
    "--syntax-character-color": role(mood, "syntax.string"),
    "--syntax-integer-color": role(mood, "syntax.number"),
    "--syntax-float-color": role(mood, "syntax.number"),
    "--syntax-bool-color": role(mood, "syntax.constant"),
    "--syntax-regexp-color": role(mood, "syntax.string"),
    "--syntax-color-color": role(mood, "syntax.constant"),
    "--syntax-url-color": role(mood, "text.accent"),
    "--syntax-attribute-value-color": role(mood, "syntax.string"),
    "--syntax-self-color": role(mood, "syntax.variable"),
    "--syntax-null-color": role(mood, "syntax.constant"),
    "--syntax-atom-color": role(mood, "syntax.constant"),
    "--syntax-unit-color": role(mood, "syntax.constant"),
    "--syntax-modifier-color": role(mood, "syntax.keyword"),
    "--syntax-operator-keyword-color": role(mood, "syntax.operator"),
    "--syntax-control-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-definition-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-module-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-operator-color": role(mood, "syntax.operator"),
    "--syntax-type-operator-color": role(mood, "syntax.type"),
    "--syntax-separator-color": role(mood, "syntax.punctuation"),
    "--syntax-angle-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-square-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-paren-color": role(mood, "syntax.punctuation"),
    "--syntax-brace-color": role(mood, "syntax.punctuation"),
    "--syntax-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-punctuation-color": role(mood, "syntax.punctuation"),
    "--syntax-heading-color": role(mood, "accent.primary"),
    "--syntax-content-separator-color": role(mood, "text.primary"),
    "--syntax-list-color": role(mood, "syntax.operator"),
    "--syntax-quote-color": role(mood, "text.secondary"),
    "--syntax-emphasis-color": role(mood, "text.primary"),
    "--syntax-strong-color": role(mood, "text.primary"),
    "--syntax-link-color": role(mood, "text.accent"),
    "--syntax-monospace-color": role(mood, "syntax.string"),
    "--syntax-content-color": role(mood, "text.primary"),
    "--syntax-inserted-color": role(mood, "status.success"),
    "--syntax-deleted-color": role(mood, "status.error"),
    "--syntax-changed-color": role(mood, "status.warning"),
    "--syntax-document-meta-color": role(mood, "text.secondary"),
    "--syntax-annotation-color": role(mood, "syntax.operator"),
    "--syntax-processing-instruction-color": role(mood, "syntax.keyword"),
    "--syntax-meta-color": role(mood, "syntax.comment"),
    "--syntax-invalid-color": role(mood, "status.error"),
    "--md-inline-code-border-color": role(mood, "border.subtle"),
    "--md-inline-code-background-color": role(mood, "surface.raised"),
    "--md-codeblock-color": role(mood, "text.primary"),
    "--md-codeblock-border-color": role(mood, "border.subtle"),
    "--md-codeblock-background-color": role(mood, "surface.raised"),
    "--md-inline-mark-text-color": role(mood, "text.primary"),
    "--md-inline-mark-background-color": role(mood, "status.notice"),
    "--md-inline-mark-underline-color": role(mood, "status.warning"),
    "--md-table-border-color": role(mood, "border.subtle"),
    "--md-table-background-color": role(mood, "surface.raised"),
    "--md-blockquote-border-color": role(mood, "accent.secondary"),
    "--md-list-mark-color": role(mood, "accent.primary"),
  };

  return `${renderHeader(mood, "syntax")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}
`;
}

function renderPreviewCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--page-background": role(mood, "surface.canvas"),
    "--text-color": role(mood, "text.primary"),
    "--link-color": role(mood, "text.accent"),
    "--link-hover-color": role(mood, "accent.primary"),
    "--border-color": role(mood, "border.subtle"),
    "--table-background": role(mood, "surface.canvas"),
    "--table-header-background": role(mood, "surface.raised"),
    "--table-header-color": role(mood, "text.primary"),
    "--md-inline-code-border-color": role(mood, "border.subtle"),
    "--md-inline-code-background-color": role(mood, "surface.raised"),
    "--md-codeblock-color": role(mood, "text.primary"),
    "--md-codeblock-border-color": role(mood, "border.subtle"),
    "--md-codeblock-background-color": role(mood, "surface.raised"),
    "--md-inline-mark-text-color": role(mood, "text.primary"),
    "--md-inline-mark-background-color": role(mood, "status.notice"),
    "--md-inline-mark-underline-color": role(mood, "status.warning"),
    "--md-table-border-color": role(mood, "border.subtle"),
    "--md-table-background-color": role(mood, "surface.raised"),
    "--md-blockquote-border-color": role(mood, "accent.secondary"),
    "--md-list-mark-color": role(mood, "accent.primary"),
    "--syntax-comment-color": role(mood, "syntax.comment"),
    "--syntax-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-string-color": role(mood, "syntax.string"),
    "--syntax-number-color": role(mood, "syntax.number"),
    "--syntax-name-function-color": role(mood, "syntax.function"),
    "--syntax-operator-color": role(mood, "syntax.operator"),
    "--syntax-punctuation-color": role(mood, "syntax.punctuation"),
  };

  return `${renderHeader(mood, "preview")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}

.mde-preview,
.mde-preview .markdown-body {
  background: ${cssValue(role(mood, "surface.canvas"))};
  color: ${cssValue(role(mood, "text.primary"))};
}

.mde-preview a {
  color: ${cssValue(role(mood, "text.accent"))};
}

.mde-preview blockquote {
  color: ${cssValue(role(mood, "text.secondary"))};
  border-left-color: ${cssValue(role(mood, "accent.secondary"))};
}

.mde-preview code,
.mde-preview pre {
  background: ${cssValue(role(mood, "surface.raised"))};
  border-color: ${cssValue(role(mood, "border.subtle"))};
}

.mde-preview table th,
.mde-preview table td {
  border-color: ${cssValue(role(mood, "border.subtle"))};
}
`;
}

function renderCss(mood: ResolvedMood, type: InkdropThemeType): string {
  if (type === "ui") return renderUiCss(mood);
  if (type === "syntax") return renderSyntaxCss(mood);
  return renderPreviewCss(mood);
}

function renderInkdropPackage(mood: ResolvedMood, type: InkdropThemeType): InkdropPackage {
  const name = packageName(mood, type);
  return {
    packageName: name,
    packagePath: name,
    moodId: mood.id,
    themeType: type,
    files: [
      { path: "package.json", content: renderPackageJson(mood, type) },
      { path: "README.md", content: renderReadme(mood, type) },
      { path: "LICENSE", content: renderLicense() },
      { path: "styles/theme.css", content: renderCss(mood, type) },
    ],
  };
}

export function renderInkdropPackages(moods: ResolvedMood[]): InkdropPackage[] {
  return moods.flatMap((mood) => THEME_TYPES.map((type) => renderInkdropPackage(mood, type)));
}
