// Hue -> Inkdrop adapter. Emits one installable Inkdrop theme package for each
// mood/theme-type pair. Inkdrop v6 themes are CSS packages with a `theme`
// metadata field (`ui`, `syntax`, or `preview`) and one or more stylesheets.

import type { SemanticToken } from "../../generated/themes";
import type { AdapterManifest } from "../contract";
import type { ResolvedMood } from "./terminal";

export const inkdropManifest = {
  supports: ["surface", "text", "border", "accent", "status", "syntax"],
  omits: {},
} satisfies AdapterManifest;

export type InkdropThemeType = "ui" | "syntax" | "preview";

export type InkdropPackage = {
  packageName: string;
  packagePath: string;
  moodId: string;
  themeType: InkdropThemeType;
  files: Array<{ path: string; content: string }>;
};

const THEME_TYPES: readonly InkdropThemeType[] = ["ui", "syntax", "preview"];

function role(mood: ResolvedMood, key: SemanticToken): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

function cssVars(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([key, value]) => `  ${key}: ${cssValue(value)};`)
    .join("\n");
}

function cssValue(value: string): string {
  return value.replace(/#[0-9A-F]{6}/gi, (hex) => hex.toLowerCase());
}

function packageName(mood: ResolvedMood, type: InkdropThemeType): string {
  if (type === "ui") return `hue-${mood.id}-theme`;
  return `hue-${mood.id}-${type}-theme`;
}

function uiThemeLabel(mood: ResolvedMood): string {
  return `Hue ${mood.id.charAt(0).toUpperCase()}${mood.id.slice(1)} Theme`;
}

function themeDescription(mood: ResolvedMood, type: InkdropThemeType): string {
  if (type === "ui") return uiThemeLabel(mood);
  const label = type.charAt(0).toUpperCase() + type.slice(1);
  return `${mood.label} ${label} Theme for Inkdrop`;
}

function renderPackageJson(mood: ResolvedMood, type: InkdropThemeType): string {
  return `${JSON.stringify(
    {
      name: packageName(mood, type),
      version: "0.1.1",
      theme: type,
      // Inkdrop needs themeAppearance to register the theme as dark/light, and
      // (for UI themes) type: "module" — matching the built-in/working themes.
      // Without these the theme silently falls back to the default.
      themeAppearance: mood.appearance,
      ...(type === "ui" ? { type: "module" } : {}),
      description: themeDescription(mood, type),
      // styleSheets are resolved relative to the package's styles/ directory, so
      // entries are bare filenames (theme.css -> styles/theme.css), not paths.
      styleSheets: ["theme.css"],
      keywords: ["inkdrop", "markdown", "hue-theme"],
      repository: {
        type: "git",
        url: "https://github.com/crafts69guy/hue-theme",
        directory: `packages/${packageName(mood, type)}`,
      },
      bugs: {
        url: "https://github.com/crafts69guy/hue-theme/issues",
      },
      homepage: "https://github.com/crafts69guy/hue-theme#readme",
      author: "crafts69guy",
      license: "MIT",
      engines: { inkdrop: "^6.x" },
    },
    null,
    2,
  )}\n`;
}

function renderReadme(mood: ResolvedMood, type: InkdropThemeType): string {
  return `# ${packageName(mood, type)}

${themeDescription(mood, type)}.

This package is generated from the Hue Theme token contract. Do not edit the
CSS by hand; update the source tokens or Inkdrop adapter and run the token build.

## Install locally

\`\`\`fish
ipm install ./packages/${packageName(mood, type)}
\`\`\`
`;
}

function renderLicense(): string {
  return `MIT License

Generated package for Hue Theme. See the repository root LICENSE for the full
license text.
`;
}

function renderHeader(mood: ResolvedMood, type: InkdropThemeType): string {
  return `/* Generated by scripts/build.ts. Do not edit.
 * ${themeDescription(mood, type)}.
 */
`;
}

function renderUiCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--primary-color": role(mood, "accent.primary"),
    "--secondary-color": role(mood, "accent.secondary"),
    "--light-primary-color": role(mood, "accent.primary"),
    "--light-secondary-color": role(mood, "text.secondary"),
    "--page-background": role(mood, "surface.canvas"),
    "--text-color": role(mood, "text.primary"),
    "--link-color": role(mood, "text.accent"),
    "--link-hover-color": role(mood, "accent.primary"),
    "--highlight-background": role(mood, "surface.selected"),
    "--highlight-color": role(mood, "text.primary"),
    "--input-background": role(mood, "surface.raised"),
    "--input-color": role(mood, "text.primary"),
    "--input-placeholder-color": role(mood, "text.secondary"),
    "--focused-form-border-color": role(mood, "accent.primary"),
    "--focused-form-muted-border-color": role(mood, "accent.secondary"),
    "--focused-outline-color": role(mood, "surface.selected"),
    "--loader-line-color": role(mood, "accent.primary"),
    "--positive-color": role(mood, "status.success"),
    "--positive-background-color": role(mood, "surface.raised"),
    "--positive-border-color": role(mood, "status.success"),
    "--positive-header-color": role(mood, "status.success"),
    "--positive-text-color": role(mood, "status.success"),
    "--negative-color": role(mood, "status.error"),
    "--negative-background-color": role(mood, "surface.raised"),
    "--negative-border-color": role(mood, "status.error"),
    "--negative-header-color": role(mood, "status.error"),
    "--negative-text-color": role(mood, "status.error"),
    "--info-color": role(mood, "status.info"),
    "--info-background-color": role(mood, "surface.raised"),
    "--info-border-color": role(mood, "status.info"),
    "--info-header-color": role(mood, "status.info"),
    "--info-text-color": role(mood, "status.info"),
    "--warning-color": role(mood, "status.warning"),
    "--warning-background-color": role(mood, "surface.raised"),
    "--warning-border-color": role(mood, "status.warning"),
    "--warning-header-color": role(mood, "status.warning"),
    "--warning-text-color": role(mood, "status.warning"),
    "--success-color": role(mood, "status.success"),
    "--success-background-color": role(mood, "surface.raised"),
    "--success-border-color": role(mood, "status.success"),
    "--success-header-color": role(mood, "status.success"),
    "--success-text-color": role(mood, "status.success"),
    "--error-color": role(mood, "status.error"),
    "--error-background-color": role(mood, "surface.raised"),
    "--error-border-color": role(mood, "status.error"),
    "--error-header-color": role(mood, "status.error"),
    "--error-text-color": role(mood, "status.error"),
    "--dark-text-color": role(mood, "text.primary"),
    "--muted-text-color": role(mood, "text.secondary"),
    "--light-text-color": role(mood, "text.secondary"),
    "--unselected-text-color": role(mood, "text.secondary"),
    "--hovered-text-color": role(mood, "text.primary"),
    "--pressed-text-color": role(mood, "text.primary"),
    "--selected-text-color": role(mood, "text.primary"),
    "--selected-border-color": role(mood, "accent.primary"),
    "--solid-border-color": role(mood, "border.subtle"),
    "--solid-selected-border-color": role(mood, "accent.primary"),
    "--primary-color-hover": role(mood, "accent.primary"),
    "--primary-color-focus": role(mood, "accent.primary"),
    "--secondary-color-hover": role(mood, "accent.secondary"),
    "--menu-background": role(mood, "surface.raised"),
    "--menu-item-text-color": role(mood, "text.primary"),
    "--menu-hover-item-background": role(mood, "surface.selected"),
    "--menu-hover-item-color": role(mood, "text.primary"),
    "--menu-active-item-background": role(mood, "surface.selected"),
    "--menu-active-item-color": role(mood, "text.primary"),
    "--popup-background": role(mood, "surface.raised"),
    "--popup-color": role(mood, "text.primary"),
    "--tooltip-background": role(mood, "surface.raised"),
    "--tooltip-color": role(mood, "text.secondary"),
    "--table-background": role(mood, "surface.canvas"),
    "--table-header-background": role(mood, "surface.raised"),
    "--table-header-color": role(mood, "text.primary"),
    "--checkbox-color": role(mood, "text.primary"),
    "--checkbox-background": role(mood, "surface.raised"),
    "--checkbox-border": `1px solid ${role(mood, "border.subtle")}`,
    "--checkbox-active-background": role(mood, "accent.primary"),
    "--checkbox-active-border-color": role(mood, "accent.primary"),
    "--dropdown-menu-background": role(mood, "surface.raised"),
    "--dropdown-menu-item-color": role(mood, "text.primary"),
    "--dropdown-hovered-item-background": role(mood, "surface.selected"),
    "--dropdown-hovered-item-color": role(mood, "text.primary"),
    "--modal-box-header-background": role(mood, "surface.raised"),
    "--modal-box-content-background": role(mood, "surface.canvas"),
    "--modal-box-actions-background": role(mood, "surface.raised"),
    "--sidebar-background": role(mood, "surface.raised"),
    "--sidebar-menu-item-inactive-background": role(mood, "surface.canvas"),
    "--sidebar-menu-item-active-background": role(mood, "surface.selected"),
    "--sidebar-menu-section-color": role(mood, "text.secondary"),
    "--sidebar-menu-item-color": role(mood, "text.secondary"),
    "--sidebar-menu-active-item-color": role(mood, "text.primary"),
    "--sidebar-sync-status-view-background": role(mood, "surface.canvas"),
    "--sidebar-sync-status-view-text-color": role(mood, "text.secondary"),
    "--scrollbar-track-background": role(mood, "surface.canvas"),
    "--scrollbar-thumb-background": role(mood, "border.subtle"),
    "--note-list-bar-background": role(mood, "surface.raised"),
    "--note-list-view-item-header-color": role(mood, "text.primary"),
    "--note-list-view-item-color": role(mood, "text.secondary"),
    "--note-list-view-item-date-color": role(mood, "accent.primary"),
    "--note-list-view-item-selected-background": role(mood, "surface.selected"),
    "--note-list-view-item-active-background": role(mood, "surface.selected"),
    "--note-search-bar-input-background": role(mood, "surface.canvas"),
    "--editor-background": role(mood, "surface.canvas"),
    "--editor-header-title-input-background": "transparent",
    "--editor-floating-actions-background": role(mood, "surface.raised"),
    "--editor-drawer-background": role(mood, "surface.raised"),
    "--header-note-menu-color": role(mood, "text.secondary"),
    "--notification-item-background": role(mood, "surface.raised"),
    "--preferences-sidebar-background": role(mood, "surface.raised"),
    "--preferences-sidebar-item-active-background": role(mood, "surface.selected"),
    "--preferences-view-background": role(mood, "surface.canvas"),
    // Text shown ON accent/colored backgrounds (selected items, filled buttons).
    // Inkdrop has no default here; without it light text on a jade fill is unreadable.
    "--inverted-text-color": role(mood, "surface.canvas"),
    "--inverted-muted-text-color": role(mood, "surface.canvas"),
    "--inverted-light-text-color": role(mood, "surface.canvas"),
    "--inverted-hovered-text-color": role(mood, "surface.canvas"),
    "--inverted-pressed-text-color": role(mood, "surface.canvas"),
    "--inverted-selected-text-color": role(mood, "surface.canvas"),
    "--inverted-unselected-text-color": role(mood, "surface.raised"),
    "--inverted-disabled-text-color": role(mood, "surface.raised"),
    // Note status dots in the note list.
    "--note-status-active": role(mood, "text.primary"),
    "--note-status-onhold": role(mood, "status.warning"),
    "--note-status-completed": role(mood, "status.success"),
    "--note-status-dropped": role(mood, "status.error"),
    // Task progress bar in the note header.
    "--task-progress-view-border-color": role(mood, "border.subtle"),
    "--task-progress-view-background-color": role(mood, "surface.raised"),
    "--task-progress-view-foreground-color": role(mood, "accent.primary"),
    "--task-progress-view-completed-color": role(mood, "status.success"),
    // ==mark== highlight (kept translucent so highlighted text stays readable).
    "--mark-background-color": `${role(mood, "status.warning")}39`,
    "--mark-border-color": `${role(mood, "status.warning")}66`,
    "--mark-color": role(mood, "text.primary"),
    "--kbd-background": role(mood, "surface.raised"),
  };

  // Tag/label chips. Inkdrop exposes 11 chromatic families; Hue has 5 chromatic
  // roles, so we group the families onto the nearest Hue hue (red↔pink, the warm
  // yellows/browns, the greens, the cyans, the violets). Each chip shows bright
  // hue text on a dark hue-tinted background derived from canvas via color-mix,
  // so the palette stays token-driven (no hardcoded chip colors).
  const tagHues: Record<string, SemanticToken> = {
    red: "status.error",
    pink: "status.error",
    orange: "status.warning",
    yellow: "status.warning",
    brown: "status.warning",
    olive: "status.success",
    green: "status.success",
    teal: "status.info",
    blue: "status.info",
    violet: "accent.secondary",
    purple: "accent.secondary",
  };
  const canvas = role(mood, "surface.canvas");
  for (const [name, hueRole] of Object.entries(tagHues)) {
    const hue = role(mood, hueRole);
    vars[`--${name}`] = hue;
    vars[`--${name}-text-color`] = hue;
    vars[`--${name}-header-color`] = hue;
    vars[`--${name}-hover`] = hue;
    vars[`--${name}-focus`] = hue;
    vars[`--${name}-down`] = hue;
    vars[`--${name}-active`] = hue;
    vars[`--${name}-background`] = `color-mix(in srgb, ${hue} 22%, ${canvas})`;
  }

  // Border treatment, Kanagawa-style two tiers: structural dividers (sidebar,
  // note list, drawers) use a near-bg hairline = surface.raised so panels read as
  // filled areas, not boxed outlines; general/floating borders use a translucent
  // rain mid-line instead of the full-strength one.
  const hairline = `color-mix(in srgb, ${role(mood, "border.subtle")} 30%, ${role(mood, "surface.raised")})`;
  const softLine = `${role(mood, "border.subtle")}66`;
  Object.assign(vars, {
    "--border-color": softLine,
    "--internal-border-color": softLine,
    "--solid-internal-border-color": softLine,
    "--strong-border-color": softLine,
    "--popup-border-color": softLine,
    "--tooltip-border-color": softLine,
    "--dropdown-menu-border-color": softLine,
    "--sidebar-border-right": `1px solid ${hairline}`,
    "--sidebar-menu-section-separator-color": hairline,
    "--note-list-bar-border-right": `1px solid ${hairline}`,
    "--note-list-view-item-separator-border": `1px solid ${hairline}`,
    "--editor-drawer-border-left": `1px solid ${hairline}`,
  });

  return `${renderHeader(mood, "ui")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}

/* Accent bar on the active note-list row, so the (subtle) selection still reads
 * at a glance. Inset shadow keeps layout stable (no reflow). */
.note-list-item-view.active {
  box-shadow: inset 2px 0 0 ${cssValue(role(mood, "accent.primary"))};
}
`;
}

function renderSyntaxCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--editor-foreground-color": role(mood, "text.primary"),
    "--editor-background-color": role(mood, "surface.canvas"),
    "--editor-caret-color": role(mood, "accent.primary"),
    "--editor-selection-background": role(mood, "surface.selected"),
    "--editor-focused-selection-background": role(mood, "surface.selected"),
    "--editor-active-line-background-color": role(mood, "surface.raised"),
    "--editor-special-char-color": role(mood, "border.subtle"),
    "--editor-spelling-error-color": role(mood, "status.error"),
    "--editor-gutter-border-right": `1px solid ${role(mood, "border.subtle")}`,
    "--editor-gutter-color": role(mood, "text.secondary"),
    "--editor-gutter-background-color": "transparent",
    "--editor-gutter-background-solid-color": role(mood, "surface.canvas"),
    "--editor-active-line-gutter-background-color": role(mood, "surface.raised"),
    "--editor-panel-background-color": role(mood, "surface.raised"),
    "--editor-panel-color": role(mood, "text.secondary"),
    "--editor-tooltip-border-color": role(mood, "border.subtle"),
    "--editor-tooltip-background-color": role(mood, "surface.raised"),
    "--editor-tooltip-autocomplete-item-selected-background-color": role(mood, "surface.selected"),
    "--editor-tooltip-autocomplete-item-selected-color": role(mood, "text.primary"),
    "--editor-inline-tooltip-color": role(mood, "text.secondary"),
    "--editor-inline-tooltip-background-color": role(mood, "surface.raised"),
    "--editor-completion-label": role(mood, "text.secondary"),
    "--editor-completion-matched-text-color": role(mood, "accent.primary"),
    "--editor-completion-detail-color": role(mood, "accent.secondary"),
    "--editor-matching-bracket-outline": `1px solid ${role(mood, "accent.secondary")}`,
    "--editor-nonmatching-bracket-outline": `1px solid ${role(mood, "status.error")}`,
    "--editor-selection-match-background-color": role(mood, "surface.raised"),
    "--editor-search-match-background-color": role(mood, "status.notice"),
    "--editor-search-match-selected-background-color": role(mood, "status.warning"),
    "--editor-search-match-selected-outline": `1px solid ${role(mood, "status.warning")}`,
    "--editor-placeholder-color": role(mood, "text.secondary"),
    "--editor-nes-ghost-color": role(mood, "text.secondary"),
    "--editor-highlight-space-color": role(mood, "surface.raised"),
    "--editor-trailing-space-background-color": role(mood, "status.error"),
    "--syntax-comment-color": role(mood, "syntax.comment"),
    "--syntax-name-color": role(mood, "text.primary"),
    "--syntax-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-name-standard-color": role(mood, "syntax.function"),
    "--syntax-name-definition-color": role(mood, "syntax.function"),
    "--syntax-name-function-color": role(mood, "syntax.function"),
    "--syntax-variable-name-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-variable-name-standard-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-definition-color": role(mood, "syntax.variable"),
    "--syntax-variable-name-function-color": role(mood, "syntax.function"),
    "--syntax-property-name-color": role(mood, "syntax.property"),
    "--syntax-property-name-constant-color": role(mood, "syntax.constant"),
    "--syntax-property-name-standard-color": role(mood, "syntax.property"),
    "--syntax-property-name-definition-color": role(mood, "syntax.property"),
    "--syntax-property-name-function-color": role(mood, "syntax.function"),
    "--syntax-tag-name-color": role(mood, "syntax.keyword"),
    "--syntax-attribute-name-color": role(mood, "syntax.property"),
    "--syntax-class-name-color": role(mood, "syntax.type"),
    "--syntax-label-name-color": role(mood, "syntax.keyword"),
    "--syntax-namespace-color": role(mood, "syntax.type"),
    "--syntax-macro-name-color": role(mood, "syntax.function"),
    "--syntax-string-color": role(mood, "syntax.string"),
    "--syntax-number-color": role(mood, "syntax.number"),
    "--syntax-literal-color": role(mood, "syntax.constant"),
    "--syntax-character-color": role(mood, "syntax.string"),
    "--syntax-integer-color": role(mood, "syntax.number"),
    "--syntax-float-color": role(mood, "syntax.number"),
    "--syntax-bool-color": role(mood, "syntax.constant"),
    "--syntax-regexp-color": role(mood, "syntax.string"),
    "--syntax-color-color": role(mood, "syntax.constant"),
    "--syntax-url-color": role(mood, "text.accent"),
    "--syntax-attribute-value-color": role(mood, "syntax.string"),
    "--syntax-self-color": role(mood, "syntax.variable"),
    "--syntax-null-color": role(mood, "syntax.constant"),
    "--syntax-atom-color": role(mood, "syntax.constant"),
    "--syntax-unit-color": role(mood, "syntax.constant"),
    "--syntax-modifier-color": role(mood, "syntax.keyword"),
    "--syntax-operator-keyword-color": role(mood, "syntax.operator"),
    "--syntax-control-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-definition-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-module-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-operator-color": role(mood, "syntax.operator"),
    "--syntax-type-operator-color": role(mood, "syntax.type"),
    "--syntax-separator-color": role(mood, "syntax.punctuation"),
    "--syntax-angle-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-square-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-paren-color": role(mood, "syntax.punctuation"),
    "--syntax-brace-color": role(mood, "syntax.punctuation"),
    "--syntax-bracket-color": role(mood, "syntax.punctuation"),
    "--syntax-punctuation-color": role(mood, "syntax.punctuation"),
    // Headings use the warm status hue (incense gold), distinct from strings/links
    // which carry the jade accent — so document structure reads in its own hue
    // instead of a single green wash.
    "--syntax-heading-color": role(mood, "status.warning"),
    "--syntax-content-separator-color": role(mood, "text.primary"),
    "--syntax-list-color": role(mood, "syntax.operator"),
    "--syntax-quote-color": role(mood, "text.secondary"),
    "--syntax-emphasis-color": role(mood, "text.primary"),
    "--syntax-strong-color": role(mood, "text.primary"),
    "--syntax-link-color": role(mood, "text.accent"),
    "--syntax-monospace-color": role(mood, "syntax.string"),
    "--syntax-content-color": role(mood, "text.primary"),
    "--syntax-inserted-color": role(mood, "status.success"),
    "--syntax-deleted-color": role(mood, "status.error"),
    "--syntax-changed-color": role(mood, "status.warning"),
    "--syntax-document-meta-color": role(mood, "text.secondary"),
    "--syntax-annotation-color": role(mood, "syntax.operator"),
    "--syntax-processing-instruction-color": role(mood, "syntax.keyword"),
    "--syntax-meta-color": role(mood, "syntax.comment"),
    "--syntax-invalid-color": role(mood, "status.error"),
    "--md-inline-code-background-color": role(mood, "surface.raised"),
    "--md-codeblock-color": role(mood, "text.primary"),
    "--md-codeblock-background-color": role(mood, "surface.raised"),
    "--md-inline-mark-text-color": role(mood, "text.primary"),
    "--md-inline-mark-background-color": role(mood, "status.notice"),
    "--md-inline-mark-underline-color": role(mood, "status.warning"),
    "--md-table-background-color": role(mood, "surface.raised"),
    "--md-blockquote-border-color": role(mood, "accent.secondary"),
    "--md-list-mark-color": role(mood, "accent.primary"),
    "--md-inline-code-border-width": "1px",
    "--md-codeblock-border-width": "1px",
    "--md-table-border-width": "1px",
    "--md-task-marker-font-weight": "bold",
    // Inkdrop renders headings from the per-level slots, not --syntax-heading-color
    // alone; derive every level/subtype from the base role like the built-in themes
    // so nothing falls back to Inkdrop's defaults.
    "--syntax-heading-font-weight": "bold",
    "--syntax-heading-1-color": "var(--syntax-heading-color)",
    "--syntax-heading-2-color": "var(--syntax-heading-color)",
    "--syntax-heading-3-color": "var(--syntax-heading-color)",
    "--syntax-heading-4-color": "var(--syntax-heading-color)",
    "--syntax-heading-5-color": "var(--syntax-heading-color)",
    "--syntax-heading-6-color": "var(--syntax-heading-color)",
    "--syntax-heading-1-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-heading-2-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-heading-3-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-heading-4-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-heading-5-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-heading-6-font-weight": "var(--syntax-heading-font-weight)",
    "--syntax-comment-font-style": "italic",
    "--syntax-line-comment-color": "var(--syntax-comment-color)",
    "--syntax-line-comment-font-style": "var(--syntax-comment-font-style)",
    "--syntax-block-comment-color": "var(--syntax-comment-color)",
    "--syntax-block-comment-font-style": "var(--syntax-comment-font-style)",
    "--syntax-doc-comment-color": "var(--syntax-comment-color)",
    "--syntax-doc-comment-font-style": "var(--syntax-comment-font-style)",
    "--syntax-arithmetic-operator-color": "var(--syntax-operator-color)",
    "--syntax-bitwise-operator-color": "var(--syntax-operator-color)",
    "--syntax-compare-operator-color": "var(--syntax-operator-color)",
    "--syntax-control-operator-color": "var(--syntax-operator-color)",
    "--syntax-definition-operator-color": "var(--syntax-operator-color)",
    "--syntax-deref-operator-color": "var(--syntax-operator-color)",
    "--syntax-logic-operator-color": "var(--syntax-operator-color)",
    "--syntax-update-operator-color": "var(--syntax-operator-color)",
    "--syntax-string-standard-color": "var(--syntax-string-color)",
    "--syntax-string-special-color": "var(--syntax-string-color)",
    "--syntax-string-constant-color": "var(--syntax-string-color)",
    "--syntax-name-special-color": role(mood, "syntax.function"),
    "--syntax-name-local-color": "var(--editor-foreground-color)",
    "--syntax-variable-name-special-color": role(mood, "status.error"),
    "--syntax-variable-name-local-color": "var(--syntax-variable-name-color)",
    "--syntax-property-name-special-color": "var(--syntax-property-name-color)",
    "--syntax-property-name-local-color": "var(--syntax-property-name-color)",
    "--syntax-emphasis-font-style": "italic",
    "--syntax-strong-font-weight": "bold",
    "--syntax-quote-font-style": "italic",
    "--syntax-link-text-decoration": "underline",
    "--syntax-strikethrough-text-decoration": "line-through",
    "--syntax-invalid-border-bottom": `1px dotted ${role(mood, "status.error")}`,
  };

  // Code blocks and tables read as filled surfaces with a near-bg hairline rather
  // than boxed outlines (Kanagawa style); panel/inline-code edges stay a soft line.
  const hairline = `color-mix(in srgb, ${role(mood, "border.subtle")} 30%, ${role(mood, "surface.raised")})`;
  const softLine = `${role(mood, "border.subtle")}66`;
  Object.assign(vars, {
    "--editor-gutter-border-right": `1px solid ${hairline}`,
    "--editor-panel-border-color": softLine,
    "--md-codeblock-border-color": hairline,
    "--md-table-border-color": hairline,
    "--md-inline-code-border-color": softLine,
  });

  return `${renderHeader(mood, "syntax")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}
`;
}

function renderPreviewCss(mood: ResolvedMood): string {
  const vars: Record<string, string> = {
    "--page-background": role(mood, "surface.canvas"),
    "--text-color": role(mood, "text.primary"),
    "--link-color": role(mood, "text.accent"),
    "--link-hover-color": role(mood, "accent.primary"),
    "--table-background": role(mood, "surface.canvas"),
    "--table-header-background": role(mood, "surface.raised"),
    "--table-header-color": role(mood, "text.primary"),
    "--md-inline-code-background-color": role(mood, "surface.raised"),
    "--md-codeblock-color": role(mood, "text.primary"),
    "--md-codeblock-background-color": role(mood, "surface.raised"),
    "--md-inline-mark-text-color": role(mood, "text.primary"),
    "--md-inline-mark-background-color": role(mood, "status.notice"),
    "--md-inline-mark-underline-color": role(mood, "status.warning"),
    "--md-table-background-color": role(mood, "surface.raised"),
    "--md-blockquote-border-color": role(mood, "accent.secondary"),
    "--md-list-mark-color": role(mood, "accent.primary"),
    "--syntax-comment-color": role(mood, "syntax.comment"),
    "--syntax-keyword-color": role(mood, "syntax.keyword"),
    "--syntax-string-color": role(mood, "syntax.string"),
    "--syntax-number-color": role(mood, "syntax.number"),
    "--syntax-name-function-color": role(mood, "syntax.function"),
    "--syntax-operator-color": role(mood, "syntax.operator"),
    "--syntax-punctuation-color": role(mood, "syntax.punctuation"),
    // Inkdrop's rendered preview reads the --mde-preview-* namespace; without these
    // headings/links/code/tables fall back to defaults.
    "--mde-preview-heading-color": role(mood, "status.warning"),
    "--mde-preview-link-color": role(mood, "text.accent"),
    "--mde-preview-em-color": role(mood, "text.primary"),
    "--mde-preview-strong-color": role(mood, "text.primary"),
    "--mde-preview-inline-code-text-color": role(mood, "syntax.string"),
    "--mde-preview-inline-code-background-color": role(mood, "surface.raised"),
    "--mde-preview-inline-code-border-color": role(mood, "border.subtle"),
    "--mde-preview-inline-code-border-width": "1px",
    "--mde-preview-codeblock-background-color": role(mood, "surface.raised"),
    "--mde-preview-codeblock-meta-background-color": role(mood, "surface.selected"),
    "--mde-preview-image-background-color": role(mood, "surface.raised"),
    "--mde-preview-inline-mark-background-color": role(mood, "status.notice"),
    "--mde-preview-inline-mark-text-color": role(mood, "text.primary"),
    "--mde-preview-inline-mark-underline-color": role(mood, "status.warning"),
    "--mde-preview-table-head-background-color": role(mood, "surface.raised"),
    "--mde-preview-table-head-text-color": role(mood, "text.primary"),
    "--mde-preview-table-row-background-color": role(mood, "surface.canvas"),
    "--mde-preview-table-row-stripe-background-color": role(mood, "surface.raised"),
  };

  // Subtle, filled-surface borders for rendered code blocks and tables.
  const hairline = `color-mix(in srgb, ${role(mood, "border.subtle")} 30%, ${role(mood, "surface.raised")})`;
  const softLine = `${role(mood, "border.subtle")}66`;
  Object.assign(vars, {
    "--border-color": softLine,
    "--md-codeblock-border-color": hairline,
    "--md-table-border-color": hairline,
    "--md-inline-code-border-color": softLine,
  });

  return `${renderHeader(mood, "preview")}
:root {
  color-scheme: ${mood.appearance};
${cssVars(vars)}
}

.mde-preview,
.mde-preview .markdown-body {
  background: ${cssValue(role(mood, "surface.canvas"))};
  color: ${cssValue(role(mood, "text.primary"))};
}

.mde-preview a {
  color: ${cssValue(role(mood, "text.accent"))};
}

.mde-preview blockquote {
  color: ${cssValue(role(mood, "text.secondary"))};
  border-left-color: ${cssValue(role(mood, "accent.secondary"))};
}

.mde-preview code,
.mde-preview pre {
  background: ${cssValue(role(mood, "surface.raised"))};
  border-color: ${cssValue(hairline)};
}

.mde-preview table th,
.mde-preview table td {
  border-color: ${cssValue(hairline)};
}
`;
}

function renderCss(mood: ResolvedMood, type: InkdropThemeType): string {
  if (type === "ui") return renderUiCss(mood);
  if (type === "syntax") return renderSyntaxCss(mood);
  return renderPreviewCss(mood);
}

function renderInkdropPackage(mood: ResolvedMood, type: InkdropThemeType): InkdropPackage {
  const name = packageName(mood, type);
  return {
    packageName: name,
    packagePath: name,
    moodId: mood.id,
    themeType: type,
    files: [
      { path: "package.json", content: renderPackageJson(mood, type) },
      { path: "README.md", content: renderReadme(mood, type) },
      { path: "LICENSE", content: renderLicense() },
      { path: "styles/theme.css", content: renderCss(mood, type) },
    ],
  };
}

export function renderInkdropPackages(moods: ResolvedMood[]): InkdropPackage[] {
  return moods.flatMap((mood) => THEME_TYPES.map((type) => renderInkdropPackage(mood, type)));
}
