// Hue → lazygit adapter. Emits one standalone YAML config per mood holding
// only gui.theme. lazygit has no include mechanism, but LG_CONFIG_FILE
// accepts a comma-separated list of configs merged left to right — so these
// fragments are meant to be listed after the user's base config, e.g.
// LG_CONFIG_FILE="~/.config/lazygit/config.yml,~/.config/lazygit/themes/hue-current.yml"
// with hue-current.yml a symlink switched per mood (same pattern as Ghostty's
// hue-current). Colors are hex strings; modifiers like `bold` ride along in
// the same list.
//
// Diff content inside lazygit is colored by the configured pager (delta,
// which follows BAT_THEME), not by gui.theme — hence syntax is omitted.

import type { AdapterManifest } from "../contract";
import type { ResolvedMood } from "./terminal";

export const lazygitManifest = {
  supports: ["surface", "text", "border", "accent", "status"],
  omits: {
    syntax: "lazygit diffs are colored by the git pager (delta follows BAT_THEME), not gui.theme",
  },
} satisfies AdapterManifest;

type ThemeEntry = { key: string; roles: string[]; modifiers?: string[] };

// lazygit gui.theme keys (v0.63). Roles are Hue semantic token names.
const THEME: ThemeEntry[] = [
  { key: "activeBorderColor", roles: ["accent.primary"], modifiers: ["bold"] },
  { key: "inactiveBorderColor", roles: ["border.subtle"] },
  { key: "searchingActiveBorderColor", roles: ["status.warning"], modifiers: ["bold"] },
  { key: "optionsTextColor", roles: ["status.info"] },
  { key: "selectedLineBgColor", roles: ["surface.selected"] },
  { key: "inactiveViewSelectedLineBgColor", roles: ["surface.raised"] },
  { key: "cherryPickedCommitFgColor", roles: ["surface.canvas"] },
  { key: "cherryPickedCommitBgColor", roles: ["accent.secondary"] },
  { key: "markedBaseCommitFgColor", roles: ["surface.canvas"] },
  { key: "markedBaseCommitBgColor", roles: ["status.warning"] },
  { key: "unstagedChangesColor", roles: ["status.error"] },
  { key: "defaultFgColor", roles: ["text.primary"] },
];

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

/** Render one lazygit theme fragment for a mood. */
function renderLazygitTheme(mood: ResolvedMood): string {
  const entries = THEME.map(({ key, roles, modifiers = [] }) => {
    const items = [...roles.map((r) => `"${role(mood, r)}"`), ...modifiers];
    return `    ${key}:\n${items.map((item) => `      - ${item}`).join("\n")}`;
  }).join("\n");

  return `# Generated by scripts/build.ts. Do not edit.
# ${mood.label} — Hue theme for lazygit; merge after the base config via
# LG_CONFIG_FILE="<base config>,<this file>".
gui:
  theme:
${entries}
`;
}

/**
 * Render every mood's lazygit fragment. Paths are relative to the
 * `packages/terminal-themes/` package root.
 */
export function renderLazygitFiles(
  moods: ResolvedMood[],
): Array<{ path: string; content: string }> {
  return moods.map((mood) => ({
    path: `lazygit/hue-${mood.id}.yml`,
    content: renderLazygitTheme(mood),
  }));
}
