import type { AdapterManifest } from "../contract";
import { mixHex } from "../color";
import type { ResolvedMood } from "./terminal";

export const tideManifest = {
  supports: ["surface", "text", "accent", "status"],
  omits: {
    border: "Tide has no prompt-wide border role separate from frame/connection colors",
    syntax: "Tide themes have no syntax-highlighting slots",
  },
} satisfies AdapterManifest;

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

function fishSet(name: string, value: string): string {
  return `set -g ${name} '${value}'`;
}

function renderTideTheme(mood: ResolvedMood): string {
  const canvas = role(mood, "surface.canvas");
  const raised = role(mood, "surface.raised");
  const selected = role(mood, "surface.selected");
  const fg = role(mood, "text.primary");
  const dim = role(mood, "text.secondary");
  const accent = role(mood, "accent.primary");
  const accent2 = role(mood, "accent.secondary");
  const success = role(mood, "status.success");
  const info = role(mood, "status.info");
  const warning = role(mood, "status.warning");
  const error = role(mood, "status.error");
  const gitStateBlend = mood.appearance === "dark" ? 0.65 : 0.45;
  const gitUnstable = mixHex(warning, canvas, gitStateBlend);
  const gitUrgent = mixHex(error, canvas, gitStateBlend);

  const lines = [
    "# Generated by scripts/build.ts. Do not edit.",
    `# ${mood.label} — Hue theme for Tide fish prompt.`,
    "",
    "# Prompt frame + connection",
    fishSet("tide_prompt_color_frame_and_connection", selected),
    fishSet("tide_prompt_color_separator_same_color", selected),
    "",
    "# Left prompt",
    fishSet("tide_os_bg_color", selected),
    fishSet("tide_os_color", fg),
    fishSet("tide_pwd_bg_color", accent),
    fishSet("tide_pwd_color_dirs", canvas),
    fishSet("tide_pwd_color_anchors", canvas),
    fishSet("tide_pwd_color_truncated_dirs", dim),
    fishSet("tide_character_color", success),
    fishSet("tide_character_color_failure", error),
    "",
    "# Git",
    fishSet("tide_git_bg_color", selected),
    fishSet("tide_git_bg_color_unstable", gitUnstable),
    fishSet("tide_git_bg_color_urgent", gitUrgent),
    fishSet("tide_git_color_branch", fg),
    fishSet("tide_git_color_operation", fg),
    fishSet("tide_git_color_dirty", fg),
    fishSet("tide_git_color_staged", fg),
    fishSet("tide_git_color_untracked", fg),
    fishSet("tide_git_color_conflicted", fg),
    fishSet("tide_git_color_stash", fg),
    fishSet("tide_git_color_upstream", fg),
    "",
    "# Right prompt status",
    fishSet("tide_status_bg_color", raised),
    fishSet("tide_status_color", success),
    fishSet("tide_status_bg_color_failure", error),
    fishSet("tide_status_color_failure", canvas),
    fishSet("tide_cmd_duration_bg_color", warning),
    fishSet("tide_cmd_duration_color", canvas),
    fishSet("tide_context_bg_color", selected),
    fishSet("tide_context_color_default", warning),
    fishSet("tide_context_color_root", error),
    fishSet("tide_context_color_ssh", info),
    fishSet("tide_jobs_bg_color", selected),
    fishSet("tide_jobs_color", success),
    fishSet("tide_direnv_bg_color", warning),
    fishSet("tide_direnv_bg_color_denied", error),
    fishSet("tide_direnv_color", canvas),
    fishSet("tide_direnv_color_denied", canvas),
    fishSet("tide_time_bg_color", accent2),
    fishSet("tide_time_color", canvas),
    "",
    "# Language/tool segments",
    fishSet("tide_node_bg_color", success),
    fishSet("tide_node_color", canvas),
    fishSet("tide_python_bg_color", selected),
    fishSet("tide_python_color", info),
    fishSet("tide_rustc_bg_color", error),
    fishSet("tide_rustc_color", canvas),
    fishSet("tide_java_bg_color", warning),
    fishSet("tide_java_color", canvas),
    fishSet("tide_ruby_bg_color", error),
    fishSet("tide_ruby_color", canvas),
    fishSet("tide_go_bg_color", info),
    fishSet("tide_go_color", canvas),
    fishSet("tide_php_bg_color", info),
    fishSet("tide_php_color", canvas),
    fishSet("tide_pulumi_bg_color", warning),
    fishSet("tide_pulumi_color", canvas),
    fishSet("tide_gcloud_bg_color", info),
    fishSet("tide_gcloud_color", canvas),
    fishSet("tide_kubectl_bg_color", info),
    fishSet("tide_kubectl_color", canvas),
    fishSet("tide_docker_bg_color", info),
    fishSet("tide_docker_color", canvas),
    fishSet("tide_aws_bg_color", warning),
    fishSet("tide_aws_color", canvas),
    fishSet("tide_nix_shell_bg_color", info),
    fishSet("tide_nix_shell_color", canvas),
    fishSet("tide_crystal_bg_color", accent2),
    fishSet("tide_crystal_color", canvas),
    fishSet("tide_elixir_bg_color", accent2),
    fishSet("tide_elixir_color", canvas),
    fishSet("tide_zig_bg_color", warning),
    fishSet("tide_zig_color", canvas),
    fishSet("tide_terraform_bg_color", accent2),
    fishSet("tide_terraform_color", canvas),
    fishSet("tide_toolbox_bg_color", accent2),
    fishSet("tide_toolbox_color", canvas),
    fishSet("tide_distrobox_bg_color", accent2),
    fishSet("tide_distrobox_color", canvas),
    fishSet("tide_shlvl_bg_color", warning),
    fishSet("tide_shlvl_color", canvas),
    fishSet("tide_private_mode_bg_color", raised),
    fishSet("tide_private_mode_color", fg),
    "",
    "# Vi mode",
    fishSet("tide_vi_mode_bg_color_default", raised),
    fishSet("tide_vi_mode_bg_color_insert", accent),
    fishSet("tide_vi_mode_bg_color_replace", error),
    fishSet("tide_vi_mode_bg_color_visual", warning),
    fishSet("tide_vi_mode_color_default", fg),
    fishSet("tide_vi_mode_color_insert", canvas),
    fishSet("tide_vi_mode_color_replace", canvas),
    fishSet("tide_vi_mode_color_visual", canvas),
  ];

  return `${lines.join("\n")}\n`;
}

function renderTideEntry(): string {
  return `# Generated by scripts/build.ts. Do not edit.
# Hue Tide theme entrypoint. Select a mood with:
#   set -g hue_flavour mua   # or huong / cung

set -q hue_flavour; or set -g hue_flavour mua

set theme_dir (dirname (status filename))
set theme_file "$theme_dir/hue-$hue_flavour.fish"

if test -f "$theme_file"
    source "$theme_file"
else
    echo "hue-tide: unknown hue_flavour '$hue_flavour'" >&2
end
`;
}

export function renderTideFiles(moods: ResolvedMood[]): Array<{ path: string; content: string }> {
  const files = moods.map((mood) => ({
    path: `tide/hue-${mood.id}.fish`,
    content: renderTideTheme(mood),
  }));
  files.push({ path: "tide/hue.fish", content: renderTideEntry() });
  return files;
}
