// Hue → tmux adapter. Emits a sourceable theme .conf per mood covering the
// status bar (powerline-style), window list, pane borders, messages, copy mode,
// and the clock. tmux themes have no status/diagnostic or syntax slots, so those
// families are omitted explicitly.

import type { AdapterManifest } from "../contract";
import type { ResolvedMood } from "./terminal";

// tmux theming maps surfaces, text, accents, and pane borders. There is no slot
// for status (success/error/...) roles or syntax highlighting in a static theme.
export const tmuxManifest = {
  supports: ["surface", "text", "accent", "border"],
  omits: {
    status: "tmux themes have no status-role (success/error/...) slots",
    syntax: "tmux themes have no syntax-highlighting slots",
  },
} satisfies AdapterManifest;

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

/** Render one sourceable tmux theme file. */
function renderTmuxTheme(mood: ResolvedMood): string {
  const canvas = role(mood, "surface.canvas");
  const raised = role(mood, "surface.raised");
  const selected = role(mood, "surface.selected");
  const fg = role(mood, "text.primary");
  const dim = role(mood, "text.secondary");
  const border = role(mood, "border.subtle");
  const accent = role(mood, "accent.primary");
  const accent2 = role(mood, "accent.secondary");

  return `# Generated by scripts/build.ts. Do not edit.
# ${mood.label} — Hue theme for tmux. Source this from tmux.conf.

# Copy mode + messages
set -g mode-style "fg=${fg},bg=${selected}"
set -g message-style "fg=${fg},bg=${raised}"
set -g message-command-style "fg=${fg},bg=${raised}"

# Panes
set -g pane-border-style "fg=${border}"
set -g pane-active-border-style "fg=${accent}"
set -g display-panes-active-colour "${accent}"
set -g display-panes-colour "${dim}"
setw -g clock-mode-colour "${accent}"

# Status bar
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=${dim},bg=${raised}"
set -g status-bg "${canvas}"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=${canvas},bg=${accent},bold] #S:#I.#P #[fg=${accent},bg=${selected},nobold,nounderscore,noitalics]#[fg=${fg},bg=${selected},bold] #(whoami) #[fg=${selected},bg=${canvas},nobold,nounderscore,noitalics]"
set -g status-right "#[fg=${selected},bg=${canvas},nobold,nounderscore,noitalics]#[fg=${dim},bg=${selected}] #[fg=${accent2},bg=${selected},nobold,nounderscore,noitalics]#[fg=${canvas},bg=${accent2},bold] #h "

# Window list
setw -g window-status-activity-style "underscore,fg=${dim},bg=${canvas}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=${dim},bg=${canvas}"
setw -g window-status-format "#[fg=${canvas},bg=${canvas}]#[default] #I  #{b:pane_current_path} #[fg=${canvas},bg=${canvas},nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=${canvas},bg=${raised}]#[fg=${accent},bg=${raised}] #I #[fg=${canvas},bg=${accent}] #{b:pane_current_path} #[fg=${accent},bg=${canvas},nobold,nounderscore,noitalics]"
`;
}

/**
 * Render every mood's tmux theme file. Paths are relative to the
 * `packages/terminal-themes/` package root.
 */
export function renderTmuxFiles(moods: ResolvedMood[]): Array<{ path: string; content: string }> {
  return moods.map((mood) => ({
    path: `tmux/hue-${mood.id}.conf`,
    content: renderTmuxTheme(mood),
  }));
}
