// Hue → Yaak adapter. Maps stable semantic roles onto Yaak's experimental
// TypeScript plugin theme API. Per the architecture policy, unsupported token
// families (syntax.*) are omitted explicitly rather than approximated.

import { STATUS_TOKENS, type StatusToken } from "../../generated/themes";
import type { AdapterManifest } from "../contract";

// Which contract families Yaak supports vs omits. syntax is omitted because
// Yaak's theme API exposes no syntax-highlighting slots.
export const yaakManifest = {
  supports: ["surface", "text", "border", "accent", "status"],
  omits: { syntax: "Yaak's theme API has no syntax-highlighting slots" },
} satisfies AdapterManifest;

export type ResolvedMood = {
  id: string;
  label: string;
  appearance: "dark" | "light";
  description: string;
  primitive: Record<string, string>;
  semantic: Record<string, string>;
};

/** The subset of Yaak's `base` theme tokens we map onto. */
export type YaakBase = {
  surface: string;
  surfaceHighlight: string;
  text: string;
  textSubtle: string;
  textSubtlest: string;
  selection: string;
  surfaceActive: string;
  border: string;
  borderSubtle: string;
  primary: string;
  secondary: string;
  info: string;
  success: string;
  notice: string;
  warning: string;
  danger: string;
};

export type YaakThemeObject = {
  id: string;
  label: string;
  dark: boolean;
  base: YaakBase;
};

/** Order is fixed so generated output is deterministic for `--check`. */
const BASE_KEYS: ReadonlyArray<keyof YaakBase> = [
  "surface",
  "surfaceHighlight",
  "text",
  "textSubtle",
  "textSubtlest",
  "selection",
  "surfaceActive",
  "border",
  "borderSubtle",
  "primary",
  "secondary",
  "info",
  "success",
  "notice",
  "warning",
  "danger",
];

function role(mood: ResolvedMood, key: string): string {
  const value = mood.semantic[key];
  if (!value) throw new Error(`Mood ${mood.id} is missing semantic role ${key}`);
  return value;
}

type YaakStatusSlot = "info" | "success" | "notice" | "warning" | "danger";

// Each status role maps to exactly one Yaak status slot, or null to omit it
// explicitly. Exhaustive over StatusToken: adding a status role is a type error
// here until mapped, and the build-time guard in statusBase fails if it is left
// out at runtime (where bun does not typecheck).
const STATUS_TO_YAAK: Record<StatusToken, YaakStatusSlot | null> = {
  "status.success": "success",
  "status.info": "info",
  "status.notice": "notice",
  "status.warning": "warning",
  "status.error": "danger",
};

function statusBase(mood: ResolvedMood): Record<YaakStatusSlot, string> {
  const base = {} as Record<YaakStatusSlot, string>;
  for (const token of STATUS_TOKENS) {
    const slot = STATUS_TO_YAAK[token];
    if (slot === undefined) {
      throw new Error(`Yaak adapter has no mapping for ${token}; map it or set null to omit`);
    }
    if (slot !== null) base[slot] = role(mood, token);
  }
  return base;
}

/** Map one Hue mood onto a Yaak theme object. Pure; no I/O. */
export function mapMoodToYaak(mood: ResolvedMood): YaakThemeObject {
  return {
    id: mood.id,
    label: mood.label,
    dark: mood.appearance === "dark",
    base: {
      surface: role(mood, "surface.canvas"),
      surfaceHighlight: role(mood, "surface.raised"),
      text: role(mood, "text.primary"),
      textSubtle: role(mood, "text.secondary"),
      textSubtlest: role(mood, "border.subtle"),
      selection: role(mood, "surface.selected"),
      surfaceActive: role(mood, "surface.raised"),
      border: role(mood, "border.subtle"),
      borderSubtle: role(mood, "surface.raised"),
      primary: role(mood, "accent.primary"),
      secondary: role(mood, "accent.secondary"),
      ...statusBase(mood),
    },
  };
}

function renderBase(base: YaakBase): string {
  return BASE_KEYS.map((key) => `        ${key}: "${base[key]}",`).join("\n");
}

function renderTheme(theme: YaakThemeObject): string {
  return `    {
      id: "${theme.id}",
      label: "${theme.label}",
      dark: ${theme.dark},
      base: {
${renderBase(theme.base)}
      },
    },`;
}

/**
 * Render the full Yaak plugin entrypoint. Output is biome-clean (double quotes,
 * trailing commas, two-space indent) so it survives `biome format`.
 */
export function renderYaakPluginSource(moods: ResolvedMood[]): string {
  const themes = moods.map(mapMoodToYaak).map(renderTheme).join("\n");
  return `// Generated by scripts/build.ts. Do not edit.
import type { PluginDefinition } from "@yaakapp/api";

export const plugin: PluginDefinition = {
  themes: [
${themes}
  ],
};
`;
}
