-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#15191B", bg = "#7FB89C", gui = "bold" },
    b = { fg = "#CFCCC2", bg = "#23282A" },
    c = { fg = "#9DA39E", bg = "#15191B" },
  },
  insert = {
    a = { fg = "#15191B", bg = "#7FB89C", gui = "bold" },
    b = { fg = "#CFCCC2", bg = "#23282A" },
    c = { fg = "#9DA39E", bg = "#15191B" },
  },
  visual = {
    a = { fg = "#15191B", bg = "#AFA3CE", gui = "bold" },
    b = { fg = "#CFCCC2", bg = "#23282A" },
    c = { fg = "#9DA39E", bg = "#15191B" },
  },
  replace = {
    a = { fg = "#15191B", bg = "#CC8079", gui = "bold" },
    b = { fg = "#CFCCC2", bg = "#23282A" },
    c = { fg = "#9DA39E", bg = "#15191B" },
  },
  command = {
    a = { fg = "#15191B", bg = "#D9BC8A", gui = "bold" },
    b = { fg = "#CFCCC2", bg = "#23282A" },
    c = { fg = "#9DA39E", bg = "#15191B" },
  },
  inactive = {
    a = { fg = "#9DA39E", bg = "#23282A" },
    b = { fg = "#9DA39E", bg = "#23282A" },
    c = { fg = "#5B6F69", bg = "#15191B" },
  },
}
