-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#F3ECD9", bg = "#356B5C", gui = "bold" },
    b = { fg = "#28251F", bg = "#E8DDC5" },
    c = { fg = "#585347", bg = "#F3ECD9" },
  },
  insert = {
    a = { fg = "#F3ECD9", bg = "#356B5C", gui = "bold" },
    b = { fg = "#28251F", bg = "#E8DDC5" },
    c = { fg = "#585347", bg = "#F3ECD9" },
  },
  visual = {
    a = { fg = "#F3ECD9", bg = "#634F75", gui = "bold" },
    b = { fg = "#28251F", bg = "#E8DDC5" },
    c = { fg = "#585347", bg = "#F3ECD9" },
  },
  replace = {
    a = { fg = "#F3ECD9", bg = "#9E342D", gui = "bold" },
    b = { fg = "#28251F", bg = "#E8DDC5" },
    c = { fg = "#585347", bg = "#F3ECD9" },
  },
  command = {
    a = { fg = "#F3ECD9", bg = "#8B5C1A", gui = "bold" },
    b = { fg = "#28251F", bg = "#E8DDC5" },
    c = { fg = "#585347", bg = "#F3ECD9" },
  },
  inactive = {
    a = { fg = "#585347", bg = "#E8DDC5" },
    b = { fg = "#585347", bg = "#E8DDC5" },
    c = { fg = "#71644C", bg = "#F3ECD9" },
  },
}
