-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#EDF3FE", bg = "#00753C", gui = "bold" },
    b = { fg = "#001F3E", bg = "#FFFFFF" },
    c = { fg = "#384B63", bg = "#EDF3FE" },
  },
  insert = {
    a = { fg = "#EDF3FE", bg = "#00753C", gui = "bold" },
    b = { fg = "#001F3E", bg = "#FFFFFF" },
    c = { fg = "#384B63", bg = "#EDF3FE" },
  },
  visual = {
    a = { fg = "#EDF3FE", bg = "#6B2FD0", gui = "bold" },
    b = { fg = "#001F3E", bg = "#FFFFFF" },
    c = { fg = "#384B63", bg = "#EDF3FE" },
  },
  replace = {
    a = { fg = "#EDF3FE", bg = "#C20A19", gui = "bold" },
    b = { fg = "#001F3E", bg = "#FFFFFF" },
    c = { fg = "#384B63", bg = "#EDF3FE" },
  },
  command = {
    a = { fg = "#EDF3FE", bg = "#A15A00", gui = "bold" },
    b = { fg = "#001F3E", bg = "#FFFFFF" },
    c = { fg = "#384B63", bg = "#EDF3FE" },
  },
  inactive = {
    a = { fg = "#384B63", bg = "#FFFFFF" },
    b = { fg = "#384B63", bg = "#FFFFFF" },
    c = { fg = "#5C7BA8", bg = "#EDF3FE" },
  },
}
