-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#101816", bg = "#82B9A2", gui = "bold" },
    b = { fg = "#EBE9DC", bg = "#16231F" },
    c = { fg = "#AFB7A8", bg = "#101816" },
  },
  insert = {
    a = { fg = "#101816", bg = "#82B9A2", gui = "bold" },
    b = { fg = "#EBE9DC", bg = "#16231F" },
    c = { fg = "#AFB7A8", bg = "#101816" },
  },
  visual = {
    a = { fg = "#101816", bg = "#A79BBC", gui = "bold" },
    b = { fg = "#EBE9DC", bg = "#16231F" },
    c = { fg = "#AFB7A8", bg = "#101816" },
  },
  replace = {
    a = { fg = "#101816", bg = "#CD6D5D", gui = "bold" },
    b = { fg = "#EBE9DC", bg = "#16231F" },
    c = { fg = "#AFB7A8", bg = "#101816" },
  },
  command = {
    a = { fg = "#101816", bg = "#D7AA5C", gui = "bold" },
    b = { fg = "#EBE9DC", bg = "#16231F" },
    c = { fg = "#AFB7A8", bg = "#101816" },
  },
  inactive = {
    a = { fg = "#AFB7A8", bg = "#16231F" },
    b = { fg = "#AFB7A8", bg = "#16231F" },
    c = { fg = "#52695F", bg = "#101816" },
  },
}
