-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#0F1D19", bg = "#6FD0A8", gui = "bold" },
    b = { fg = "#D6DAD0", bg = "#182A24" },
    c = { fg = "#98A59C", bg = "#0F1D19" },
  },
  insert = {
    a = { fg = "#0F1D19", bg = "#6FD0A8", gui = "bold" },
    b = { fg = "#D6DAD0", bg = "#182A24" },
    c = { fg = "#98A59C", bg = "#0F1D19" },
  },
  visual = {
    a = { fg = "#0F1D19", bg = "#A9A0C8", gui = "bold" },
    b = { fg = "#D6DAD0", bg = "#182A24" },
    c = { fg = "#98A59C", bg = "#0F1D19" },
  },
  replace = {
    a = { fg = "#0F1D19", bg = "#D38478", gui = "bold" },
    b = { fg = "#D6DAD0", bg = "#182A24" },
    c = { fg = "#98A59C", bg = "#0F1D19" },
  },
  command = {
    a = { fg = "#0F1D19", bg = "#DCBB80", gui = "bold" },
    b = { fg = "#D6DAD0", bg = "#182A24" },
    c = { fg = "#98A59C", bg = "#0F1D19" },
  },
  inactive = {
    a = { fg = "#98A59C", bg = "#182A24" },
    b = { fg = "#98A59C", bg = "#182A24" },
    c = { fg = "#587168", bg = "#0F1D19" },
  },
}
