-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#001523", bg = "#00CF6A", gui = "bold" },
    b = { fg = "#E5F4FF", bg = "#001F3E" },
    c = { fg = "#9DB4D4", bg = "#001523" },
  },
  insert = {
    a = { fg = "#001523", bg = "#00CF6A", gui = "bold" },
    b = { fg = "#E5F4FF", bg = "#001F3E" },
    c = { fg = "#9DB4D4", bg = "#001523" },
  },
  visual = {
    a = { fg = "#001523", bg = "#8A7BFF", gui = "bold" },
    b = { fg = "#E5F4FF", bg = "#001F3E" },
    c = { fg = "#9DB4D4", bg = "#001523" },
  },
  replace = {
    a = { fg = "#001523", bg = "#FF5A63", gui = "bold" },
    b = { fg = "#E5F4FF", bg = "#001F3E" },
    c = { fg = "#9DB4D4", bg = "#001523" },
  },
  command = {
    a = { fg = "#001523", bg = "#FF8D00", gui = "bold" },
    b = { fg = "#E5F4FF", bg = "#001F3E" },
    c = { fg = "#9DB4D4", bg = "#001523" },
  },
  inactive = {
    a = { fg = "#9DB4D4", bg = "#001F3E" },
    b = { fg = "#9DB4D4", bg = "#001F3E" },
    c = { fg = "#456C94", bg = "#001523" },
  },
}
