-- Generated by scripts/build.ts. Do not edit.

return {
  normal = {
    a = { fg = "#F3ECD9", bg = "#3A6E5F", gui = "bold" },
    b = { fg = "#3C372C", bg = "#E8DDC5" },
    c = { fg = "#66604F", bg = "#F3ECD9" },
  },
  insert = {
    a = { fg = "#F3ECD9", bg = "#3A6E5F", gui = "bold" },
    b = { fg = "#3C372C", bg = "#E8DDC5" },
    c = { fg = "#66604F", bg = "#F3ECD9" },
  },
  visual = {
    a = { fg = "#F3ECD9", bg = "#6A5384", gui = "bold" },
    b = { fg = "#3C372C", bg = "#E8DDC5" },
    c = { fg = "#66604F", bg = "#F3ECD9" },
  },
  replace = {
    a = { fg = "#F3ECD9", bg = "#A6403A", gui = "bold" },
    b = { fg = "#3C372C", bg = "#E8DDC5" },
    c = { fg = "#66604F", bg = "#F3ECD9" },
  },
  command = {
    a = { fg = "#F3ECD9", bg = "#8B5C1A", gui = "bold" },
    b = { fg = "#3C372C", bg = "#E8DDC5" },
    c = { fg = "#66604F", bg = "#F3ECD9" },
  },
  inactive = {
    a = { fg = "#66604F", bg = "#E8DDC5" },
    b = { fg = "#66604F", bg = "#E8DDC5" },
    c = { fg = "#8C846F", bg = "#F3ECD9" },
  },
}
