-- Generated by scripts/build.ts. Do not edit.

local M = {}

local cache = {}

-- Resolve a mood id from an explicit arg, the active colorscheme, or Mưa.
local function resolve(mood)
  if mood then
    return mood
  end
  local name = vim.g.colors_name
  return (name and name:match("^hue%-(.+)$")) or "mua"
end

--- Flat semantic map for a mood, e.g. `raw()["accent.primary"]`.
function M.raw(mood)
  local entry = require("hue.palette")[resolve(mood)]
  if not entry then
    error("hue: unknown mood '" .. tostring(mood) .. "'")
  end
  return entry.semantic
end

--- Semantic palette grouped by family, e.g. `get().accent.primary`.
function M.get(mood)
  local id = resolve(mood)
  if cache[id] then
    return cache[id]
  end
  local grouped = {}
  for role, value in pairs(M.raw(id)) do
    local family, name = role:match("^(.-)%.(.+)$")
    grouped[family] = grouped[family] or {}
    grouped[family][name] = value
  end
  cache[id] = grouped
  return grouped
end

return M
