-- Generated by scripts/build.ts. Do not edit.

local M = {}

M.options = { default = nil, transparent = false }

function M.setup(opts)
  M.options = vim.tbl_extend("force", M.options, opts or {})
end

-- Groups whose background is cleared when `transparent` is enabled.
local TRANSPARENT_GROUPS = {
    "Normal",
    "NormalNC",
    "NormalFloat",
    "FloatBorder",
    "FloatTitle",
    "SignColumn",
    "FoldColumn",
    "EndOfBuffer",
    "MsgArea",
    "Pmenu",
    "PmenuSbar",
    "PmenuExtra",
    "PmenuKind",
    "TelescopeNormal",
    "TelescopeBorder",
    "NeoTreeNormal",
    "NeoTreeNormalNC",
    "WhichKeyFloat",
}

function M.load(mood)
  mood = mood or M.options.default
  local palette = require("hue.palette")
  local entry = palette[mood]
  if not entry then
    error("hue: unknown mood '" .. tostring(mood) .. "'")
  end

  if vim.g.colors_name then
    vim.cmd("highlight clear")
  end
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.o.background = entry.appearance
  vim.g.colors_name = "hue-" .. mood

  for index, color in ipairs(entry.terminal) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end

  local groups = require("hue.groups")(entry.semantic)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end

  if M.options.transparent then
    for _, group in ipairs(TRANSPARENT_GROUPS) do
      local hl = vim.api.nvim_get_hl(0, { name = group, link = false })
      hl.bg = nil
      hl.ctermbg = nil
      vim.api.nvim_set_hl(0, group, hl)
    end
  end
end

-- Public API for user configs building custom highlights from Hue colors.
-- See lua/hue/colors.lua (palette access) and lua/hue/util.lua (color math).
local colors = require("hue.colors")
M.colors = colors.get
M.raw = colors.raw
M.util = require("hue.util")

return M
