-- Generated by scripts/build.ts. Do not edit.

local M = {}

M.options = { default = nil }

function M.setup(opts)
  M.options = vim.tbl_extend("force", M.options, opts or {})
end

function M.load(mood)
  mood = mood or M.options.default
  local palette = require("hue.palette")
  local entry = palette[mood]
  if not entry then
    error("hue: unknown mood '" .. tostring(mood) .. "'")
  end

  if vim.g.colors_name then
    vim.cmd("highlight clear")
  end
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.o.background = entry.appearance
  vim.g.colors_name = "hue-" .. mood

  for index, color in ipairs(entry.terminal) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end

  local groups = require("hue.groups")(entry.semantic)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

return M
