-- Generated by scripts/build.ts. Do not edit.

local M = {}

local function clamp(n)
  return math.max(0, math.min(255, n))
end

local function to_rgb(hex)
  hex = hex:gsub("#", "")
  return tonumber(hex:sub(1, 2), 16), tonumber(hex:sub(3, 4), 16), tonumber(hex:sub(5, 6), 16)
end

local function to_hex(r, g, b)
  return string.format("#%02X%02X%02X", math.floor(clamp(r) + 0.5), math.floor(clamp(g) + 0.5), math.floor(clamp(b) + 0.5))
end

-- Linear sRGB blend; `alpha` is the weight of `fg` over `bg`.
function M.blend(fg, bg, alpha)
  local fr, fg_, fb = to_rgb(fg)
  local br, bg_, bb = to_rgb(bg)
  return to_hex(alpha * fr + (1 - alpha) * br, alpha * fg_ + (1 - alpha) * bg_, alpha * fb + (1 - alpha) * bb)
end

function M.darken(hex, amount, bg)
  return M.blend(hex, bg or "#000000", amount)
end

function M.lighten(hex, amount)
  return M.blend(hex, "#FFFFFF", amount)
end

return M
