# Generated by scripts/build.ts. Do not edit.
# Hue Tide theme entrypoint. Select a mood with:
#   set -g hue_flavour mua   # or huong / cung

set -q hue_flavour; or set -g hue_flavour mua

set theme_dir (dirname (status filename))
set theme_file "$theme_dir/hue-$hue_flavour.fish"

if test -f "$theme_file"
    source "$theme_file"
else
    echo "hue-tide: unknown hue_flavour '$hue_flavour'" >&2
end
